### ISSUE TITLE
define_task_block_restore_thread should take execution policy, not executor

### ISSUE THREAD

**Issue by hkaiser** [executors/executors#10]
The task-block creation function `define_task_block_restore_thread` should expect a `execution_policy` (as defined by Parallelism TS) instead of an executor:

```
template<class ExPolicy, class F>
void define_task_block_restore_thread(ExPolicy && exec, F&& f);
```

This not only specifies a (default) executor (as associated with the policy), but also makes the task-block conform to the semantics of the parallel algorithms. 

In HPX, we allow for instance to specify asynchronous execution policies with a task block, etc.

**Comment by mjgarland** [comment]
I think our current model is that execution policies are only used when the control structure is creating multiple agents.  The policy then defines the semantics of these agents with respect to each other.  Since this is only creating one agent, I'm not sure what the policy specifies.  What did you have in mind exactly?

**Comment by hkaiser** [comment]
@mjgarland task blocks may create more than one agent. The `run` function may be called more than once, each of these calls may create a new one.

**Comment by fraggamuffin** [comment]
Makes sense to me.

**Comment by mjgarland** [comment]
I think we will need input from people who have implementation experience with `task_block` or similar functionality.  I imagine there could be subtle issues related to whether the implementation can guarantee the execution policy semantics across all invocations of `run` within the block.

**Comment by hkaiser** [comment]
@mjgarland Would the implementation experience we have in HPX be sufficient (see https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/parallel/task_block.hpp)? What additional pieces of information are you looking for?

**Comment by jaredhoberock** [comment]
We decided that we do want to specify the interoperation between executors and standard control structures such as `define_task_block`, but that we would not provide such specifications in P0443
