### ISSUE TITLE
Consider adding a concurrent thread pool to the proposed list.

### ISSUE THREAD

**Issue by ccmysen** [executors/executors#102]
One significant flaw in the current proposal is that we don't have a replacement executor for the default one used by std::async. While i'm not proposing that we introduce a generic growing thread pool, i wonder if it is worthwhile to introduce the concept of a thread-per-request executor of some sort (it could still pool threads, but would guarantee that each new task has a thread).

Or we could go even simpler and just introduce the "thread per request" executor that has the property that it's a drop in replacement for async.

**Comment by hcedwar** [comment]
This is definitely a significant flaw in my book.  One of my major objectives for a well-founded executor proposal is to expose the implied executor that is used by std::async and is hidden in the runtime.

**Comment by mjgarland** [comment]
If I understand correctly, the two of you have suggested different things.  Chris is suggesting that there be an executor class whose semantics match what `std::async` currently does.  Carter is suggesting that implementations expose how they implement `std::async` as an executor.  The difference being that different implementations at the moment might currently implement `std::async` somewhat differently, therefore implying that different implementations would expose executors  that behaved somewhat differently.  In other words, Chris is talking about a replacement executor with compatible semantics and Carter is talking about an interface to this existing implementation (whatever that is).  Is this accurate?

**Comment by mjgarland** [comment]
And should either of these bear a particular relationship with the concept of a "system executor" that has been discussed in some of the past executor papers?

**Comment by hcedwar** [comment]
@mjgarland : exactly, I want implementations to explicitly expose their async mechanism as an executor.  With that codes could refactor to explicitly use this executor with no change in functionality, then be able to accept replacement executors to gain better control over execution.

**Comment by mjgarland** [comment]
Would you truly find that useful?  For example, if I understand libc++ correctly, it's current implementation creates a new thread every time you call `std::async`.  Is that really an executor that codes would want to explicitly use?  It seems like it would seldom be preferable to an actual thread pool.

**Comment by hcedwar** [comment]
For real applications that transition from an "old way" to a "new way" having an incremental and well-defined migration path is critical.

1. add default async executor to all async calls

1. verify program runs as before

1. incrementally replace default async executor with something better

1. verify correctness along the way

**Comment by ccmysen** [comment]
Agree that we are talking about different types of executors, though logically they are similar.

A caching thread pool has a lot of the same properties as the thread-per-request in async, but is missing one key one: that thread use is visible to code (you can get a thread id, or see stored thread locals) -- so you get the concurrency property that almost everyone wants, but not uniqueness.

if we want just one then the drop-in-replacement is probably the best starting point. i'd argue that both are useful.

**Comment by jaredhoberock** [comment]
In the meantime we've decided that a hypothetical `dynamic_thread_pool` with stronger forward progress guarantees would be a good idea, and that idea should be explored in a separate paper.
