### ISSUE TITLE
Should ExecutorWorkTracker make any statement about the expected behavior of executor?

### ISSUE THREAD

**Issue by ccmysen** [executors/executors#145]
Right now it simply states that it's a way to track possible future work, but not what the executor will do with that information. We can state what the code should expect to be able to do between the call to on_work_started and on_work_finished.

**Comment by jaredhoberock** [comment]
`ExecutorWorkTracker` no longer exists, but the `outstanding_work` properties are related. We added a note indicating that we expect the executor to convey some information to the underlying `.context()`. Exactly what that might mean depends on an elaboration of requirements for `ExecutionContext`, which will be explored in a separate paper.
