### ISSUE TITLE
Include a default constructor to thread pool 

### ISSUE THREAD

**Issue by ccmysen** [executors/executors#158]
Preference from committee to have a default thread pool constructor which does something implementation defined (allowing for a default "2x num cores" or something similar).

This _might_ motivate having a way to query the number of threads currently joined to the pool in case you need to join more to it.

**Comment by jaredhoberock** [comment]
We decided not to include an automatically-sizing constructor for `static_thread_pool`. A fancier scheme (e.g. `dynamic_thread_pool`) can be explored in a separate paper.
