### ISSUE TITLE
then_execute has unclear meaning from its name

### ISSUE THREAD

**Issue by LeeHowes** [executors/executors#159]
During voting today it occurred to me that I had to look up what then_execute means from the text, rather than from its wording.

It turns out to be then_async_execute, according to the text. This has two issues:
1) I don't know what it might block. The predecessor task or the caller?
2) There is no way to ensure it won't block, which is a fundamental property.

So don't we really need then_async_post, then_post, then_async_execute, then_execute (with one-way meaning) and *maybe* even then_sync_post, then_sync_execute (ie then_blah(...).get()). Which is odd I realise but consistent, and also against the theme of simplicity, but we definitely need to at least be consistent in some dimension.

**Comment by LeeHowes** [comment]
As just mentioned in issue 161 it probably doesn't make sense to have a then_sync_execute anyway, so this is really then_execute (ie not then_post and then_defer) so should follow the blocking trait.

We should make it clear that the blocking semantics defined by the trait apply to then_execute, and precisely where they apply: I would suggest that if the executor guarantees no blocking then both the completing task and the caller of then_execute are guaranteed not to block. If it does not, then neither is.

**Comment by jaredhoberock** [comment]
I think that agrees with my understanding. To be clear, what do you mean by "completing task"?

**Comment by LeeHowes** [comment]
Given the pseudo code:
main{ 
e.execute(foo).then_execute(bar);
}

foo (or at least, a running instance of the closure called foo, which we can call foo for simplicity) is the completing task, that satisfies the future. main is the task calling then_execute. There are potentially unwanted blocking points both when main calls then_execute and when foo sets a value on the promise.

For example, we don't want to have foo be executing on a remote thread, set the value on the promise after then_execute is called and block that thread. Equally, having then_execute block is the same problem for main as having .execute block in the first place.

We could decouple these two blocking points, but to keep things simple making it clear that either both may block, or neither may block, is enough.

**Comment by jaredhoberock** [comment]
I think Lee's pseudocode would look more like this given P0443's current design:

```
main
{
  auto future = e.twoway_execute(foo);
  future.then(bar);
}
```

Which executor `.then(bar)` will use, and the blocking behavior that implies, will be explored in a separate paper.
