### ISSUE TITLE
Add ongoing discussion for post/defer

### ISSUE THREAD

**Issue by chriskohlhoff** [executors/executors#177]
Something like the following:
<hr/>

Execution functions named "post" and "defer" have identical semantics. Specifically this means that, in generic code (i.e. code where the executor type is a template parameter), calls to post and defer may be interchanged without altering program semantics or correctness. Where post and defer differ is in the information conveyed to the executor about the caller's intent: the use of "defer" indicates that the submitted function object represents a continuation of the caller.

Concrete executor implementations can use this information to optimize performance. For example, a simple static thread pool can halve the synchronization performed per submitted function object (e.g. reducing the cost per function from 55ns to 26ns on recent x86-64 CPUs running Linux) when these function objects are chained. For applications that consist of long chains of short continuations, this represents a significant improvement in throughput and latency. 

However, all other execution function names represent distinct semantic guarantees; "post" and "defer" are the exceptions. To address this inconsistency, we may consider providing only one of these functions (i.e. "post") and to introduce a hinting mechanism to convey the additional information to an executor. Ideally, this mechanism would be extensible to allow other hints to be introduced in the future (e.g. a hint to indicate that a submitted function object benefits from CPU affinity).

As an example of established practice, the Boost.Asio library uses an ADL customization point, named `asio_handler_is_continuation` to provide functionality equivalent to "defer". The library's executors apply this function to all submitted function objects to determine when the optimization may be applied.

**Comment by ccmysen** [comment]
Adding into a pull request to pull into the paper, but i think we should seriously consider the design where defer is a hint of sort -- either as a template parameter (not great), or possibly some sort of a type constraint on the function which allows us to wrap the function with additional parameters so you could create a DeferredFunction<Function> type which can be interpreted as a hint as well.

I think the fact that this is basically the only semantically different behavior makes it seem particularly strange to support as basically the only performance function variant.

**Comment by jaredhoberock** [comment]
Thanks ChrisK, I have incorporated this into the explanatory paper.

I agree that we need some sort of general purpose mechanism for communicating parameters to the executor which have no semantic meaning in generic code. Adding a time delay to execution would be another example of a parameter in this category of "hints". However, I'm unsure whether such hints should be parameters to the execution functions. I kind of prefer a world where all parameters to execution functions have semantic meanings that all executors must understand.

The model I've imagined is that it is the executor itself that encapsulates these kinds of hinting parameters. If a client needs to create execution agents with a different set of hints, then the client should reparameterize the executor before calling the execution function.

**Comment by ccmysen** [comment]
I don't think that it should require reparameterizing the who executor since this doesn't really indicate that the executor itself has changed, but rather is a change in desired semantics from the client-side -- that feels like something configurable on the function call to me, but we can discuss separately.

**Comment by jaredhoberock** [comment]
The properties mechanism resolved these issues.
