### ISSUE TITLE
Possible design aproach for post/defer & other customization points

### ISSUE THREAD

**Issue by ccmysen** [executors/executors#185]
Clarifying the set of primitives, we basically have a few main concerns which are still being conflated a bit.

We have:
post
defer
execute
sync_execute (sort of)

as the primitives for blocking, non-blocking, and possibly blocking the caller.

Then we have a few primitives for one-way vs. two-way sync vs. two-way deferred (no prefix, sync_, and async_).

And then obviously the bulk vs. non-bulk.

My proposal would potentially be to clear up the execute to not be conflated with two-way execution and to drop defer as a primitive and turn that into a hint.

which would leave us with the following primitive names:
post
execute
sync

we could decide if a one-way sync even makes sense, but i dont know that it does.

then ignoring the then_ variants we end up with a cleaner division of semantics, with the special statement that blocking is always two-way, even in the void case because there's no differentiation (if there's a return value you can chose to ignore it anyway).

**single-dispatch:**
**one-way**
execute _(possibly-blocking)_
post _(non-blocking)_
**two-way**
sync _(blocking)_
async_execute _(possibly-blocking)_
async_post _(non-blocking)_

**multiple-dispatch:**
**one-way**
bulk_execute _(possibly-blocking)_
bulk_post _(non-blocking)_
**two-way**
bulk_sync _(blocking)_
bulk_async_execute _(possibly-blocking)_
bulk_async_post _(non-blocking)_

This leaves the question of how to parameterize the defer concept -- i think we should consider whether we want to create a special function type which is in indication that the function has a relationship to the caller and we can use specialized function wrappers to indicate other semantic differences. This carries some overhead and some issues about what it means when you wrap a specialized type in another specialized type -- so we'd need to think about this a bit, but it makes function specialization really simple because the execution functions are already parameterized on the function type and so having a type:
template <typename F>
DeferredFunction {
  decay_t<F> operator()
};

Anyway, this last bit we can discuss a bit more, but thoughts on this configuration?

**Comment by ccmysen** [comment]
Though to be honest, i think in this model, async as a modifier is a little weird because there's also a "sync" still, but i think it's still makes sense.

**Comment by jaredhoberock** [comment]
The properties scheme was the way we ended up refactoring the execution functions.
