### ISSUE TITLE
Hinting mechanism

### ISSUE THREAD

**Issue by chriskohlhoff** [executors/executors#191]
# What is a "hint"?

In our executor design, a user executes some function `F` by submitting it to an executor `E` using an execution function `S`:

    S(E, F ...)

A hint is some characteristic or property of this submission that is intended by the user, but that does not impact executor semantics *in a generic context*.

When using an executor generically (typically when the Executor is a template parameter or deduced type), the contract between user code and executor is determined by the executor requirements defined in our proposal. Something is a hint if it does not affect whether these semantic requirements are met. Instead, a hint determines behaviour that is left unspecified by the requirements.

For example, when submitting a function object using the one-way function `post()`:

    post(ex, f);

under our executor requirements, generic code can make no assumptions about whether `f` will be eagerly scheduled or not. All it can assume is the caller will not be blocked pending completion of `f`. However, we may still want to suggest to the executor whether we would prefer eager or deferred scheduling: this is a hint. The executor is free to honour or ignore the request without violating the executor requirements, and generic user code cannot make assumptions either way.

Examples of hints include:

* Whether the submitted function represents a continuation of the caller. (Currently expressed as `post` vs `defer`.)
* The preferred allocator to be used to store state associated with the submitted task. (Currently expressed using an allocator parameter on certain execution functions.)

Conversely, some user choices do affect semantics in a generic context. For example, the selection of an execution function for its directionality or blocking properties. Non-hints (i.e. things that determine behaviour under the executor requirements) are expressed through function names and parameters.

# Hints in concrete contexts

Concrete executor implementations may guarantee whether hints will be honoured, and code using these executors can make assumptions based on these guarantees. We may also choose to specify exactly how some standard executors will honour particular hints, i.e. we may decide to constrain implementations by referring to hints in our "Effects" clauses.

# Specifying hints

When defining a hint, the standardese must specify a contract for how the hint will be used. For example an allocator hint will specify exactly when and how an executor is permitted to use the allocator.

# Requirements for a hinting mechanism

The design of a hinting mechanism must satisfy the following requirements:

* Extensible
* Survivable
* Forwardable
* Overridable
* Defaultable and ignorable

## Extensible

The hinting mechanism should permit the creation of new hints, by both user code and future additions to the standard.

## Survivable

A control structure or customisation point may pass a submitted function directly to another control structure, customisation point, or execution function. For example:

    template <class Executor, class Function>
    void my_control_structure(const Executor& ex, Function f)
    {
      execution::execute(ex, f);
    }

The hints associated with the submission of `f` should still be available to the implementation of `execute`. This includes arbitrary hints that may not yet even exist, i.e. survivability must support extensibility.

## Forwardable

A control structure or customisation point may adapt a submitted function before passing it to another control structure, customisation point, or execution function. For example:

    template <class Function>
    class logging_function
    {
      Function f;

      void operator()()
      {
        std::cout << "before\n";
        f();
        std::cout << "after\n";
      }
    };

    template <class Executor, class Function>
    void logging_execute(const Executor& ex, Function f)
    {
      logging_function<Function> f1{std::move(f)};
      execution::execute(ex, std::move(f1));
    };

The adapter must be able to forward hint requests to caller's code. This must support arbitrary hints, i.e. forwardability must support extensibility.

## Overridable 

A control structure or customisation point may adapt a submitted function before passing it to another control structure, customisation point, or execution function, as shown in the "Forwardable" section above. The adapter implementer may be aware of certain hints and wish to override them. Otherwise, any other (arbitrary) hints should be forwardable.

## Defaultable and ignorable

All hints must have a sensible default value which corresponds to the "ignored" case. This allows intermediate adapters (e.g. executor adapters, and in particular a runtime polymorphic executor) to drop the hint without affecting behaviour in a generic context.

Defaultability also enables extensibility, in that we can create a new hint without affecting existing code that is unaware of it.

# Proposed design

The proposed design is based around the idea that a hint is associated with a submitted function.

## Hint type requirements

A Hint is a function object of class type. Each different hint has a distinct type. A Hint `h` is callable as `h(f)`, and this expression yields the hint's default value.

For example, a hint that indicates that a function object would benefit from scheduling affinity might look something like this:

    class affine
    {
    public:
        bool operator() const { return false; }
    };

## Standard hints

The standard hints are defined in a new sub-namespace.

    namespace std {
    namespace experimental {
    inline namespace concurrency_v2 {
    namespace execution {
    namespace hints {

      constexpr is_continuation_t is_continuation;
      constexpr allocator_t allocator;

    } // namespace hints
    } // namespace execution
    } // inline namespace concurrency_v2
    } // namespace experimental
    } // namespace std

with suitable implementations that define the default values:

    class is_continuation_t
    {
    public:
      bool operator() const { return false; }
    };

    class allocator_t
    {
    public:
      std::allocator<void> operator() const
        { return std::allocator<void>(); }
    };

## `get_hint` customisation point

The hint customisation point is passed a function `f` and a hint object `h`, i.e. the expression `get_hint(f, h)` is valid. The customisation point works as follows:

* If `f.get_hint(h)` is valid, returns the result of that expression.
* Otherwise, if `get_hint(f, h)` is valid (when performed in a namespace that does not include... etc.), returns the result of that expression.
* Otherwise, returns `h()`.

## Implementing a hint as a user

User can associate a hint with their function object by defining as a member function:

    struct my_function
    {
      void operator()() { ... }

      my_allocator<void> get_hint(execution::hints::allocator_t) const
        { return my_allocator<void>(); }
    };

or as a free function:

    struct my_function
    {
      void operator()() { ... }
    };

    my_allocator<void> get_hint(const my_function&, execution::hints::allocator_t)
      { return my_allocator<void>(); }

## Impact on execute functions and executor implementations

The one-way execution functions would now need only take the function object:

    class my_executor
    {
    public:
      // ...

      template <class Function>
      void execute(Function f) const
      {
        // ...
      }
    };

All hints can be obtained by applying the `get_hint` customisation point to the function. For example, here is how a concrete executor might use the allocator hint:

    class my_execution_context
    {
      friend class my_executor;

      struct queued_function_base
      {
        shared_ptr<queued_function_base> next_;
        // ...
      };

      template <class Function>
      struct queued_function : queued_function_base
      {
        explicit queued_function(Function f) : f_(std::move(f)) {}
        Function f_;
        // ...
      };

      void do_enqueue(shared_ptr<queued_function_base> f)
      {
        // ...
      }
    };

    class my_executor
    {
      my_execution_context& context_;

    public:
      // ...

      template <class Function>
      void execute(Function f) const
      {
        auto a = execution::get_hint(f, execution::hints::allocator);
        auto p = std::allocate_shared<
          my_execution_context::queued_function<Function>>(
            a, std::move(f));
        context_.do_enqueue(p);
      }
    };

### Extensible

This design supports extensibility by allowing users to define their own hint classes.

### Survivable

Hints are associated with the submitted function object, and so are automatically accessible wherever the function object goes.

### Forwardable

Function object adapters can forward arbitrary hints:

    template <class Function>
    class logging_function
    {
      Function f;

    public:
      void operator()()
      {
        std::cout << "before\n";
        f();
        std::cout << "after\n";
      }

      template <class Hint>
      auto get_hint(Hint h) const
        { return execution::get_hint(f, h); }
    };

### Overridable

Function object adapters can override specific hints while forwarding others:

    template <class Function>
    class logging_function
    {
      Function f;

    public:
      void operator()()
      {
        std::cout << "before\n";
        f();
        std::cout << "after\n";
      }

      template <class Hint>
      auto get_hint(Hint h) const
        { return execution::get_hint(f, h); }

      my_allocator<void> get_hint(execution::hints::allocator_t) const
        { return my_allocator<void>(); }
    };

### Defaultable and ignorable

The hint type requirements require them to be function objects which yield a default value.

**Comment by ccmysen** [comment]
I have been thinking about the possible approaches to do hinting and it seems like it comes down to a few key questions about what purpose the hints serve.

One way or another, it seems like the hints live in the connection between the task and the executor. In thinking about the mechanism, i wonder where exactly the hints should live (as in, is it part of the task or in the binding of a task to an executor)?

For example, what if we create a task-id like concept where there is a unique task identifier which allows the executor to bind hints to a given task? It seems like this would be more awkward for the executor to track properly, but if the executor choses to ignore all hints, or only take certain hints, it could chose to only remember the hints which it can handle. This appears to be what you were aiming at with execution::hints::get_hint such that anyone could query for it, but allows wrapped versions of the same function to continue to operate correctly, and it binds the hints to a particular execution of the function (there's not a requirement in current executors that execution happens just once, and you may chose to re-bind hints).

This brings up one more semantic question about hints -- are they introspectable (as in, would a given function be able to forward its own hints to tasks created during execution)? I can see a number of situations where you are creating sequences of work on the same executor for which you would like to forward the hints to the sequence of operations. I don't quite know how you would communicate this, but if you explicitly passed an identifier to the function you could look up the hints.


As an aside, it seems like in the future, we will likely want to be able to query about supported hints as well, much like the hard constraints of an executor. For example, if we were to support a priority hint in the future, many executors will never support it, but it would likely allow one to switch behavior knowing that a priority hint would actually have an effect would graduate from a hint to a full on semantic difference, but doesn't change the fact that the code accepts that not all executors will support such behavior and a particular caller is okay with a soft requirement.

**Comment by jaredhoberock** [comment]
The properties mechanism we adopted this is the way we support hints.
