### ISSUE TITLE
Is there a version with then_execute for polymorphic Wrapper for two-way?

### ISSUE THREAD

**Issue by fraggamuffin** [executors/executors#20]
Is there a version with then_execute for polymorphic Wrapper for two-way?
as there is a 2 way wrapper for async_execute
Or is it WIP?

**Comment by jaredhoberock** [comment]
The current version of the paper has two polymorphic executor wrappers: `one_way_executor` and `two_way_executor`. Each of these has a single function that creates an execution agent. I don't believe anything prevents us from elaborating these wrappers with additional member functions corresponding to the executor customization points.

If we did decide to elaborate these wrappers, I'd suggest first merging the two polymorphic wrappers as suggested by #32.

**Comment by ccmysen** [comment]
btw -- if it's fine, i'll work on the change to make a complete mirror of the standard executors in the polymorphic form (haven't had a chance to do this).

**Comment by jaredhoberock** [comment]
This issue has been resolved in the meantime -- `executor` has a `.then_execute` function.
