### ISSUE TITLE
How does OneWayExecutor fulfill a future<T>?

### ISSUE THREAD

**Issue by TBBle** [executors/executors#236]
Looking  at [P0443R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0443r1.html)

*OneWayExecutor* is described as:
> The OneWayExecutor requirements specify requirements for executors which create execution agents without a channel for awaiting the completion of a submitted function object and obtaining its result. [Note: That is, the executor provides fire-and-forget semantics. --end note]

And yet, `executor_future<Executor, T>::type` is
> if `is_one_way_executor<Executor>` is `true`, `std::future<T>`;

(#188 has since fixed this to be `std::experimental::future`)

Since the only well-defined user of `executor_future` is the `std::async( E, F, ...)`, and this is defined in terms of `async_post`, `std::async( E, F, ... )` only makes sense with a *NonBlockingOneWayExecutor*. The handwavey description of `std::experiemental::future::then(E, F)` says "*OneWayExecutor* that cannot block in `.execute()`" which I'm pretty sure is also *NonBlockingOneWayExecutor*.

So the line I quoted above from `executor_future<Executor, T>::type` probably should be:
> if `is_non_blocking_one_way_executor<Executor>` is `true`, `std::future<T>`;

which should make `async( OneWayExecutor, F, ... )` ill-formed, I guess. Although that's also specified at the moment.

---

If that's the case, then it'd be nice if the proposal also suggested something like `spawn( E, F, ...)`, to expose the `execute` behaviour to the general user, in the same way `async( E, F, ...)` exposes `async_post`. 

It's not really an interaction with existing behaviours, it's the executorified version of
```cpp
template< class Function, class... Args >
void spawn( Function&& f, Args&&... args ) {
  auto t = std::thread{std::forward<Function>(f), std::forward<Args>(args)...};
  t.detach();
}
```

and I'd expect `spawn( issue_8_executor, ... )` to be pretty-much the above behaviour, given an executor as described by #8. I assume it'd be as simple as:

> Equivalent to
`auto __g = bind(std::forward<Function>(f), std::forward<Args>(args)...);`
`execution::execute(exec, [__g = move(__g)]{ INVOKE(__g); });`

**Comment by TBBle** [comment]
Looking at the R2 branch, this doesn't appear to have changed. All the explanatory text that gives context on `executor_future` also talks about the two-way executor methods only.

**Comment by jaredhoberock** [comment]
Hi, thanks for the suggestions. Briefly, the way we expect one-way executors to compose with two-way interfaces like `async` is by introducing a promise-future pair. The agent created through the one-way executor, after executing the user's task, would also fulfill the promise.

We're currently working from the rebind-prototype branch, which includes significant changes to the design, and is described by [P0688](http://wg21.link/P0688). We expect to merge that branch into R2 soon.
