### ISSUE TITLE
Some editorial issues

### ISSUE THREAD

**Issue by TBBle** [executors/executors#237]
I noticed these in R1, but they appear to still be present in the R2 branch.

---

One occurrence of "presedence":
> Whenever there is a conflict of semantics the presedence is resolved in the order below.

---

The *only* difference I could find between "post" and "defer" is what looks like another copy-and-paste error in the same table:

`never_blocking_execute`:
> Creates an execution agent with forward progress guarantees of executor_execution_mapping_category_t<X> **which** invokes DECAY_COPY( std::forward<F>(f))() at most once, with the call to DECAY_COPY being evaluated in the thread that called never_blocking_execute. 

`never_blocking_continuation_execute`:
> Creates an execution agent with forward progress guarantees of executor_execution_mapping_category_t<X> invokes DECAY_COPY( std::forward<F>(f))() at most once, with the call to DECAY_COPY being evaluated in the thread that called never_blocking_continuation_execute. 

I think the lack of 'with' in the `never_blocking_continuation_execute` version isn't supposed to change the meaning, and it seems non-grammatical to me.

**Comment by jaredhoberock** [comment]
These issues were resolved after introducing the properties scheme.
