### ISSUE TITLE
Thoughts on .then with new executor design

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#238]
This was taken from a discussion on the mailing list regarding concerns about how to represent the full capabilities of the new executor design through continuations:

> I'm not entirely clear on the semantics of then_execute, particularly on whether a future type should be required to always provide the then_execute and bulk_then_execute functions or whether this should be derived from the properties of it's associated executor.
> 
> My original thinking was that the latter approach could be useful for allowing future types to only provide the interface that they require for their assocaited executor. However after thinking about this some more I think this approach would be problematic as it creates a relationship between the then property and the twoway property where in order to perform direct continuations from a future you would have to require the then property on the twoway executor which produced the future. For example:
> 
> oneway_executor exec;
> rebind(exec, twoway, then).twoway_execute(...).then_execute(...); // then_execute would only be possible if the then property was required on the original executor.
> 
> This would also be further complicated when considering the bulk property, as you would similarly have to require the bulk property on the executor which produced the future in order for the future to call bulk_then_execute.
> 
> I think a better approach would be to require that any future type provide then_execute and bulk_then_execute and require them to provide adaptations if the associated executor does not provide the functions natively. For example:
> 
> oneway_execute exec;
> rebind(exec, twoway).twoway_execute(...).bulk_then_execute(...); // here bulk_then_execute would have to rebind the assocaited executor with the bulk property and adapt if nessesary.
> 
> Though this may raise the issue of whether the require cutomisation point can adapt a polymorphic executor, as I asume the future type in this case would have to store the associated executor polymorphically.

> I agree that simply adding additional then_ functions is not ideal, and it could be problematic for introducing extenions to the interface at a later date, I think we should perhaps aim for a more generic approach that is more extensible.
> 
> An idea that I have been considering is one where rather than having the future types provide then_execute and bulk_then_execute, and potentially then_require and then_prefer, we could have the future type require just a single then function which would return the associated executor. That executor could then be used for a range of different functions, including rebinding with additional properties. For example:
> 
> oneway_executor exec;
> rebind(exec, twoway).twoway_execute(...).then().rebind(bulk).bulk_execute(...); // here the then function would rebind the associated executor to require the then property and then return it.
> 
> I believe @ccmysen also had some concerns about how the relationship between twoway executors and continuations and whether those can be separated and also about how to avoid proliferating then_ functions in the design.

**Comment by jaredhoberock** [comment]
We expect that the interaction between `.then()` and `.then_execute()` will be explored in a separate paper.
