### ISSUE TITLE
How would an executor handle a require for context specific hints?

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#239]
During a discussion on the mailing list the question of how an executor would handle a require for a context specific hint:

> How would the require customization point treat the request for a property or a hint which is execution context specific and not natively supported by that executor's associated execution context, and furthermore what the relationship between executor and execution context should look like in relation to properties? I imagine that in most cases this could be resolved by adapting the executor, provided both the executor and execution context are of the same implementation. However this would become more complicated when considering interoperability between executor implementations, though that's an entire issue of it's own.
> 
> One solution could be to require that properties requested through require must be provided by all executors (either natively or through some kind of adaptation) and hints requested through prefer are optional and do not have to be provided. So anything that is execution context specific could be provided as a hint so it is ignored if not supported, though this may limit the levels of support executors are allowed to provide.

Though I think perhaps this is already possible as in the example of using adaptors that @chriskohlhoff showed during the last call.

**Comment by jaredhoberock** [comment]
I think the answer is that an executor would support a context-specific property only if the specific context is also the executor's context. If the property is specific to some other type of property, then the executor simply need not support that property.
