### ISSUE TITLE
Should the executor associated with a future be the rebound executor?

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#240]
Should the executor associated with the future type returned from a twoway execution function of a rebound executor be the rebound executor or the original executor? For example:

```
oneway_executor exec;
rebind(exec, twoway).twoway_execute(...).then_execute(...); // should this use the oneway executor or the twoway executor?
```

I think it would make most sense to use the rebound executor though there may be an argument for the alternative.

**Comment by jaredhoberock** [comment]
The interaction between `.then()` and `.then_execute()` will be explored separately from P0443.
