### ISSUE TITLE
How to remove a property from an executor?

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#241]
We don't currently provide any way to remove a property, for example if you wanted to revert back to the default allocator, or remove a preference for thread_execution_mapping. This could be useful for direct continuations or in an API where executors are passed around and you don't necessarily know which properties are attached to a particular executor.

This was discussed on the last call and I believe the conclusion was that in general properties should be additive unless specified to be mutually exclusive. Though this still doesn't provide a way to remove the properties that are not mutually exclusive.

One solution could be to add default property variants for those that don't have them. Another could be to allow temporary properties or hints, particularly for hints that are provided to prefer.

**Comment by AerialMantis** [comment]
I've created a merge request for adding default properties for execution mapping and the allocator: https://github.com/executors/issaquah_2016/pull/254.

**Comment by jaredhoberock** [comment]
The proposed resolution was merged.
