### ISSUE TITLE
Feedback on call to prefer

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#242]
It would be useful to provide some way to get feedback on whether a call to prefer was successful for particular hints, for cases where this cannot be determined at compile-time, for example when a runtime value is provided to the hint.

**Comment by jaredhoberock** [comment]
It seems like a general mechanism to query executors for properties would support this goal: to discern whether a call to `prefer` had an effect, query the result executor for the preferred property.

**Comment by jaredhoberock** [comment]
We decided that `query` is the channel for receiving this feedback.
