### ISSUE TITLE
Should we have a property for forward progress guarantees between the submitted function and the caller?

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#243]
Perhaps we should include a property for forward progress guarantees between submitted functions and the caller, I believe this could be useful as a way of providing boost blocking.

**Comment by AerialMantis** [comment]
I've created a merge request that adds the property for requesting forward particular progress guarantees between the caller thread and the execution agents spawn by the execution function: https://github.com/executors/issaquah_2016/pull/253.

I also started looking into defining the meanings of the two properties that deal with forward progress guarantees though i'm not sure if the properties we have at the moment cover the different forward progress guarantees.

From my reading of the execution policy wording, though i'm no expert on these:
* `execution::sequenced_policy` requires all execution to occur in the calling thread.
* `execution::parallel_policy` requires any spawned threads to have at least parallel forward progress guarantees if the caller thread had concurrent forward progress guarantees.
* `execution::parallel_unsequenced_policy` requires any spawned threads to have at least weakly parallel forward progress guarantees.

The execution policies also put requirements on sequencing and which threads are executed on, which in some cases conflict with the thread mapping property. I imagine the execution policies will be implemented in terms of executor properties, so perhaps the properties we define should be directly based on the forward progress guarantees:

```
  constexpr struct bulk_concurrent_execution_t {} bulk_concurrent_execution;
  constexpr struct bulk_parallel_execution_t {} bulk_parallel_execution;
  constexpr struct bulk_weakly_parallel_execution_t {} bulk_weakly_parallel_execution;

  constexpr struct caller_concurrent_execution_t {} bulk_concurrent_execution;
  constexpr struct caller_parallel_execution_t {} bulk_parallel_execution;
  constexpr struct caller_weakly_parallel_execution_t {} bulk_weakly_parallel_execution;
```

**Comment by AerialMantis** [comment]
In the last call we were discussing whether or not a property for forward progress with the caller is necessary.

We decided that if the caller is in pool, then the forward progress guarantees of the caller must match the forward progress guarantees between execution agents. Though we may still need a property for forward progress guarantees with the caller when the caller is not in pool.

As discussed in the last call I've written up a potential use case for then this property could be useful. One case where I though the property would be useful was the same case we were discussing the `unsafe_mode` for. Where you have a twoway never blocking executor which does not support oneway execution natively but is adapted to a oneway executor, meaning there is no way to boost block the function to ensure it executes when the forward progress guarantees are not concurrent.

Another way of dealing with this problem could be to require certain forward progress guarantees on the executor using a caller forward progress guarantees property:

In the example below the function is not guaranteed to execute.
```
// twoway executor which cannot natively support oneway execution
twoway_executor twoWayExec;

// oneway never blocking executor provided through adaptation of a twoway executor
auto oneWayExec = require(twoWayExec, oneway, never_blocking);

// adaptation drops future, so there's no way to channel for synchronisation
oneWayExec.execute(function);
```

In the example below the function is guaranteed to execute as concurrent forward progress with the caller is required.
```
// twoway executor which cannot natively support oneway execution
twoway_executor twoWayExec;

// oneway never blocking executor provided through adaptation of a twoway executor with forward progress guarantees
auto oneWayExec = require(twoWayExec, oneway, never_blocking, caller_concurrent_execution);

// adaptation drops but concurrent forward progress is guaranteed
oneWayExec.execute(function);
```

**Comment by jaredhoberock** [comment]
The proposed resolution was merged.
