### ISSUE TITLE
Respond to Toronto concerns over oneway

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#247]
Straw poll: OK with `oneway` as-is?

```
SF F N A SA
4  6 6 2 3
```

Carter: EAs should have some sort of handle to work somewhere. Work should not just be dropped on the floor.
Billy: I don’t like the idea of trying to build `oneway` from `twoway` or vice versa without some way to perform boost-blocking.

**Comment by jaredhoberock** [comment]
P0433R2's `execution::require` does not adapt twoway executors to oneway executors, so this concern only applies to the oneway -> twoway case.

The issue is that an adaptation from oneway to twoway includes introducing a future. However, because neither `std::future` nor `std::experimental::future` provide a way to boost-block the task, there is no guarantee that calling `.wait()` on the future will ever complete.

The consensus from the August 4 executors telecon was that the underlying problem should really be solved by a better-designed future.

For the executors TS, our tentative plan is to provide a way for users to opt into adaptations from oneway executors to twoway, future-returning interfaces. One way to do with would be through providing a new executor property indicating that `execution::require` has permission to adapt the oneway executor. This additional property can be provided at the same time as `twoway` in the same call to `execution::require`.

**Comment by chriskohlhoff** [comment]
I have created #257 to show a possible implementation of an opt-in property.

**Comment by jaredhoberock** [comment]
We incorporated the opt-in property, so closing.
