### ISSUE TITLE
Alternative naming for require & prefer

### ISSUE THREAD

**Issue by ccmysen** [executors/executors#260]
Naming question for alternative ideas:

- rebind + maybe_rebind
- mutate + maybe_mutate

**Comment by chriskohlhoff** [comment]
transmute + maybe_transmute

**Comment by chriskohlhoff** [comment]
ome other choices from http://www.thesaurus.com/browse/transmute:

transform + maybe_transform
transfigure + maybe_transfigure
transmogrify + maybe_transmogrify (this one certainly stands out)
metamorphose + maybe_metamorphose

**Comment by jaredhoberock** [comment]
adapt + maybe_adapt
embue + maybe_embue
introduce + maybe_introduce
require_property + prefer_property

**Comment by chriskohlhoff** [comment]
One thing worth noting is that "require" doesn't necessarily require any transformation/adaptation/mutation/other-word-here. If the executor type already satisfies the requirement then it can be returned as-is.

**Comment by ccmysen** [comment]
expect + maybe_expect
modify + maybe_modify
convert + maybe_convert
conform + maybe_conform (try_conform)
recast + maybe_recast
apply + maybe_apply
expropriate + maybe_expropriate
appropriate + maybe_appropriate
rework + maybe_rework

**Comment by chriskohlhoff** [comment]
See pull requests #261 and #262 for how `transform_executor` and `transform` would look.

**Comment by jaredhoberock** [comment]
Another option would be to retain `prefer` and choose a synonym for `require`, e.g. `insist`, `demand`

**Comment by jaredhoberock** [comment]
For what it's worth, during the Albuquerque meeting, no one suggested to me the idea of changing the names `require` and `prefer`.

**Comment by ccmysen** [comment]
Yes, interestingly enough...even in LEWG...
