### ISSUE TITLE
Current properties interface limits querying properties with values

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#264]
We generally defined properties as an instance of a struct, which the customization points can be overloaded for to support a particular property. This means that both the `require` and `prefer` customization points and the `query` customization point can use the same properties.

For example, with:

```
constexpr struct possibly_blocking_t {} possibly_blocking;
```

you can do:

```
prefer(exec, possibly_blocking);  // ok
query(exec, possibly_blocking);  // ok
```

However when it comes to properties which take a value we define the interface as a function which returns the instance of the struct containing the value. However this interface is not compatible with the `query` customization point as you cannot pass a function template to a customization point.

For example with:

```
struct default_allocator_t {} default_allocator;
  template<class ProtoAllocator> struct allocator_t { ProtoAllocator alloc; };
  template<class ProtoAllocator> constexpr allocator_t<ProtoAllocator> allocator(const ProtoAllocator& a) { return {a}; }
```

then the following fails:

```
prefer(exec, allocator(std::allocator<void>{}));  // ok
query(exec, allocator);  // error
```

To solve this we can define the `allocator` property as a global function object instead:

```
struct default_allocator_t {} default_allocator;
template<class ProtoAllocator> struct allocator_t { ProtoAllocator alloc; };
struct { template<class ProtoAllocator> constexpr allocator_t<ProtoAllocator> operator()(const ProtoAllocator& a) { return {a}; } } allocator;
```

**Comment by jaredhoberock** [comment]
Makes sense to me. When defining what properties are, we could insert some wording to ensure that they are always the type of thing which can be passed as a function parameter.

**Comment by jaredhoberock** [comment]
We've fixed the design of the allocator property which prompted this issue.
