### ISSUE TITLE
Idea to allow execution::query to always compile

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#275]
In writing up some example code:

```
// request a (user-defined) priority
auto maybe_prioritized_ex = execution::prefer(ex, priority(0));

// inspect the result of prefer()
assert(execution::query(maybe_prioritized_ex, priority) == 0);
```

I noticed that even though the `prefer` call will always succeed, if `maybe_prioritized_ex` doesn't have the `priority` property, then the second line will fail to compile.

We could enable all such calls to `execution::query()` to succeed if we defined a type to indicate the lack of a particular property. Say, `no_such_property`, or similar [c.f. [`std::experimental::nonesuch`](http://en.cppreference.com/w/cpp/experimental/nonesuch)].

**Comment by AerialMantis** [comment]
I like this idea, with this we could say that `query` must always compile just like `prefer` but if the executor `E` does not support the property `P` then `query_member_result_t<E, P>` resolves to a specific type. It would be helpful as well if the type could give you an error code for why the property isn't supported such as `std::error_code`.
