### ISSUE TITLE
executor_shape is too limited

### ISSUE THREAD

**Issue by hkaiser** [executors/executors#28]
The definition of executor_shape seems to be too limited. In our experience it is very helpful if the shape object passed to the bulk interfaces can represent any sequence (i.e. anything supporting `begin()`/`end()`).

**Comment by mjgarland** [comment]
Should all shape types be _required_ to support begin()/end()?  Would that exclude types that we would otherwise want to allow (e.g., std::tuple's)?

**Comment by AerialMantis** [comment]
For our use case it's important that the shape be a type capable of describing a multi dimensional range, so I feel requiring any shape type to support begin() / end() may be limiting as well.

**Comment by jaredhoberock** [comment]
@AerialMantis: We (from NVIDIA) would also like executors to be able to create multidimensional index spaces, and we want to pursue that feature in a follow-up to the minimal paper. The current proposal ought to be forward-compatible with that idea.
