### ISSUE TITLE
Investigate simplifying allocator_t & allocator_wrapper_t

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#282]
From Jeffrey Y:

> Is there a reason to define a struct allocator_t and allocator_wrapper_t instead of a "template<PA> struct allocator { allocator(PA); };"?

**Comment by AerialMantis** [comment]
The reason we have separate types for `allocator_t` and `allocator_wrapper_t` is to allow the same property name `allocator` to be used for both the `require`/`prefer` customisation poitns and the `query` customisation point. So you can do both `auto exec_with_alloc = exec.prefer(allocator(myAllocator))` and `auto alloc = exec_with_alloc.query(allocator)`.

We describe this in a note in the paper:

```
[Note: As the allocator(ProtoAllocator) property requires a value to be provided when being set, it is required to be implemented such that it is callable with the ProtoAllocator parameter when used in require or prefer where the customization points accepts the result of the function call operator of allocator_t; allocator_wrapper_t and is passable as an instance when used in query where the customization point accepts an instance of allocator_t. --end note]
```
Should we explain this better?

**Comment by jaredhoberock** [comment]
Perhaps a better name than `allocator_wrapper_t` could offer sufficient explanation. Or maybe there is a way that we could introduce only a single name by combining `allocator_t` with `allocator_wrapper_t`.

For example:

```
template<class ProtoAllocator>
struct allocator_t
{
  ProtoAllocator a;
};

template<>
struct allocator_t<void>
{
  template<class ProtoAllocator>
  allocator_t<ProtoAllocator operator()(const ProtoAllocator& a)
  {
    return allocator_t<ProtoAllocator>{a};
  }
};

allocator_t<void> allocator;
```

In other words, it could work exactly the same as the status quo, but only introduce the name `allocator_t`.

**Comment by AerialMantis** [comment]
Yeah, this works really nicely; and means we just have a single property name, I think we should go for this.

I can do a merge request for this if you like.

**Comment by jaredhoberock** [comment]
Yes, please do submit a pull request.
