### ISSUE TITLE
execution::default_allocator and execution::allocator can be constexpr

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#286]
From Louis D:

>louis d: XXX minor issue: you can make default_allocator and allocator constexpr

**Comment by AerialMantis** [comment]
I believe this should be resolved by https://github.com/executors/executors/pull/329.

The global instance of `allocator_t<void>` is now constexpr, which covers `default_allocator_t` which is now `allocator_t<void>`. I have not made `allocator_t<void>::operator(ProtoAllocator)` constexpr yet as that would require `std::allocator` to have a constexpr constructor as well, though we can always revisit this.
