### ISSUE TITLE
Polymorphic executor's constructor should be disabled if assigned executor cannot fulfill requirements

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#292]
If the target executor assigned to a polymorphic executor cannot fulfill all of the property requirements, then the polymorphic executor's constructor should be removed from the overload set.

**Comment by AerialMantis** [comment]
Need to check whether we want to have a compile-time error or sfinae the constructor when the requirements cannot be fulfilled.

**Comment by jaredhoberock** [comment]
Specifically, we need to check the Albuquerque minutes to see who provided this feedback, and what the actual desire was.
