### ISSUE TITLE
Proposed wording for executor equality

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#317]
After discussing what it means for an executor to be equal I started thinking about some of the issues we discussed and thought I'd have a go at what the potential wording might look like.

**Non-polymorphic executors**

Now that the context is simply another optional property to an executor it seems like equality comes down to two factors.

For any two executors X and Y:
* Is the type of X the same as the type of Y?
* Does X contain the same set of properties as Y?

So from these questions, we can derive the following rules:
1. If the type of X is not the same as the type of Y then X and Y cannot be equal because even if X and Y were to have the same set of properties, they could be implemented differently or be provided through adaptations.
2. If X does not contain the same set of properties as Y then X and Y cannot be equal because the difference in properties could enforce different semantics.
3. If the type of X is the same as the type of Y and X contains the same set of properties as Y then you can be sure that X and Y are equal as they have the same properties which means they will enforce the same semantics and they are the same type which means they will be implemented in the same way.

From these rules we can derive the definition:

> For any two non-polymorphic executors; X and Y, X is equal to Y if the type of X is the same as the type of Y and X contains the same set of properties as Y.

**Polymorphic executors**

Now if we look at equality between polymorphic executors, this becomes more complicated, as we also have to consider the type of polymorphic executors as well as the executors which they wrap.

We can assume that the previous rules 1 and 2 still apply for the executors wrapped within the polymorphic executors, however, how does rule 3 still apply in the context of polymorphic executors? We could potentially allow two polymorphic executors of different types to still be equally providing the wrapped executors are the same type and contain the same set of properties, however, this would require constraints on the polymorphic executor such that it cannot adapt the semantics of the wrapped executor in any way and would also require that ordering of properties have no bearing on the semantics which is still an ongoing discussion. Therefore, to keep things simple for now we can require the polymorphic executors to be the same type.

For any two polymorphic executors PX and PY wrapping executors X and Y respectively:
* Is the type of PX the same as the type of PY?
* Is the type of X the same as the type of Y?
* Does X contain the same set of properties as Y?

So from these questions, we can derive the following rules:
1. If the type of X is not the same as the type of Y then PX and PY cannot be equal because even if X and Y were to have the same set of properties, they could be implemented differently or be provided through adaptations.
2. If X does not contain the same set of properties as Y then PX and PY cannot be equal because the difference in properties could enforce different semantics.
3. If the type of PX is not the same as the type of PY then PX and PY cannot be equal because X or Y could be adapted by PX or PY respectively.
4. If the type of PX is the same as the type of PY, the type of X is the same as the type of Y and X contains the same set of properties as Y then you can be sure that PX and PY are equal as they have the same properties which means they will enforce the same semantics and they are the same types which means they will be implemented in the same way.

From these rules we can derive the definition:

> For any two polymorphic executors; PX and PY, and their respective non-polymorphic executors which PX and PY wrap; X and Y, PX is equal to PY if the type of PX is the same as the type of PY, the type of X is the same as the type of Y and X contains the same set of properties as Y.

Now, this could be a valid wording, however, this definition is a little problematic, because if the executor wrapped by a polymorphic executor is type-erased then the type and properties of that executor are unobservable. One potential solution would be to replace the requirements on the executor wrapped by a polymorphic executor with requirements on the last executor which the polymorphic executor was constructed with or assigned to.

The previous definition can then be altered to:

> For any two polymorphic executors; PX and PY, and the respective non-polymorphic executors which PX and PY were last constructed from or assigned to; X and Y, PX is equal to PY if the type of PX is the same as the type of PY, the type of X is the same as the type of Y and X contains the same set of properties as Y.

Furthermore, this definition doesn't cover the case of equality between a polymorphic executor and a non-polymorphic executor.

For this we can add an additional definition:

> For any polymorphic executor PX, the respective non-polymorphic executor which PX was last constructed from or assigned to; X, and any non-polymorphic executor Y, PX is equal to Y if the type of X is the same as the type of Y and X contains the same set of properties as Y

**Additional points to consider**

* Another area of concern for this definition is in whether or not a polymorphic executor can be used in a call to the customization point `require`, as this would alter the executor wrapped by the polymorphic executor making the requirements of the definition unobservable. Though as the result of `require` must be known at compile-time which is not possible with the polymorphic executor as the wrapped executor type can be type-erased, it seems unlikely this ability will be required. However, if it is then we will need to alter the wording further to incorporate this.
* As mentioned earlier this definition assumes that we do not require that two polymorphic executors be equal in the case of the polymorphic executors being different types but the respective non-polymorphic wrapped in those executors being the same executor type and containing the same set of properties. However, if this is required then we would have to loosen the definition to allow this.

**Final wording**

> For any two non-polymorphic executors; X and Y, X is equal to Y if the type of X is the same as the type of Y and X contains the same set of properties as Y.
> For any polymorphic executor; PX, the respective non-polymorphic executor which PX was last constructed from or assigned to; X, and any non-polymorphic executor Y, PX is equal to Y if the type of X is the same as the type of Y and X contains the same set of properties as Y.
> For any two polymorphic executors; PX and PY, and the respective non-polymorphic executors which PX and PY were last constructed from or assigned to; X and Y, PX is equal to PY if the type of PX is the same as the type of PY, the type of X is the same as the type of Y and X contains the same set of properties as Y.

**Comment by jaredhoberock** [comment]
Thanks for the analysis, Gordon.

> If the type of X is the same as the type of Y and X contains the same set of properties as Y then you can be sure that X and Y are equal as they have the same properties which means they will enforce the same semantics and they are the same type which means they will be implemented in the same way.

I think this assumption is not correct in all scenarios. Equal properties may not be sufficient for equal executors, because some types of executors may choose to store state outside of the properties system. So, property equality is necessary, but not a sufficient condition for executor equality.

**Comment by AerialMantis** [comment]
That's a good point, so you could have two executors, with the same type and containing the same set of properties, but have other state inside which differs. I wonder how we could word this so that additional state within executors must also be equal, as this will likely be implementation specific.

A possible solution could be to require that an executor only have state which is represented via a property value, though perhaps this would be too restrictive.

**Comment by jaredhoberock** [comment]
I don't think we need to insist anything about executor state external to properties. It would be impossible to enforce, for one thing. I think the executor type should simply decide whether or not any additional state matters to equality.

I'd suggest adapting the wording used for Allocator equality from Table 31 of the IS:

> returns true only if storage allocated from each can be deallocated via the other. operator== shall be reflexive, symmetric, and transitive, and shall not exit via an exception.

We could say something like: returns true if all of the executors' properties are equal. operator== shall be reflexive, symmetric, and transitive, and shall not exit via an exception.

**Comment by AerialMantis** [comment]
So we could state that the properties of the two executors must be equal rather than just being them have the same set of properties. This makes sense for named executor types, but it might be more complicated for the polymorphic executor where the type may not be known. Should we leave it up to the implementation to evaluate whether two properties from different executors are equal? Or if we were to say executor equality is derived from property executor, would that raise the question of what does it mean for properties to be equal?

**Comment by jaredhoberock** [comment]
Why would equality be especially difficult for polymorphic executors?

Suppose we want to test polymorphic executors A and B, which contain concrete executors a & b.

If the types of a & b differ, then A and B are not equal. If the types of a & b are the same, then the polymorphic executor returns the result of a == b.

It's a & b which need to worry about comparing their properties, right?

**Comment by AerialMantis** [comment]
My thought was how would the wording describe equality for an object which is type-erased, though perhaps I'm overthinking this and it can simply be handled by the implementation.

I tried to find a precedent for this somewhere else in the standard, so I looked at the wording for `std::any`. For `std::any` the variable stored inside is described as the `contained object`, so perhaps we could use a similar wording when describing an executor stored within a polymorphic executor. Unfortunately `std::any` doesn't provide an equality operator so I couldn't compare wording for it. However, it does provide a `type()` member function which returns the type of the `contained object`:

* Returns: typeid(T) if *this has a contained object of type T, otherwise typeid(void).

Which is then used to describe whether the `any_cast` is valid:

* Throws: bad_any_cast if operand.type() != typeid(remove_reference_t<T>).

Perhaps we could use a similar wording to this; we could introduce a member function on the polymorphic executor such as `executor_type()` which provides the type of the `contained executor object`. And then the equality for the polymorphic executor could be written in terms of `exec.executor_type()` and `typeid(Executor)`. I believe this is close to how @chriskohlhoff's prototype is currently doing it.

>It's only a & b which need to worry about comparing their properties, right?

Shouldn't we also require that `A` and `B` also be the same type? Because you could have a situation where you have two different polymorphic executor types which both contain the same type; in which case `a == b` but `A != B`. This wouldn't be an issue if we required that the polymorphic executor cannot adapt or introduce semantics to the contained executor, which perhaps we want to do?

**Comment by chriskohlhoff** [comment]
Might be worth looking at std::function. It has operator== and performs similar type erasure.

**Comment by chriskohlhoff** [comment]
Ah sorry, no it only has operator== for nullptr.

**Comment by chriskohlhoff** [comment]
Note that we do already have `target_type()` and `target()` in our current specification. and our operator== is specified in terms of the "target" as a term of art.

**Comment by ccmysen** [comment]
realizing looking at the code that my comment on the email chain may already be captured in the code. But is there a problem with the implementation where we do a type check then a cast for equality comparison on the underlying executor. 

Is that not sufficient?
