### ISSUE TITLE
Issue with polymorphic_executor<SupportableProperties...> form

### ISSUE THREAD

**Issue by chriskohlhoff** [executors/executors#326]
Let's assume we have the following piece of code which performs some task immediately if it can, and otherwise asynchronously in the background.

    template<class Executor>
    void do_async_work(
        Executor ex,
        Callback callback)
    {
      if (try_work() == done)
      {
        // Work completed immediately, invoke callback.
        execution::require(ex,
            execution::single,
            execution::oneway,
          ).execute(callback);
      }
      else
      {
        // Perform work in background. Track outstanding work.
        start_background_work(
            execution::prefer(ex,
              execution::outstanding_work),
            callback);
      }
    }

This function can be used with an inline executor which is defined as follows:

    struct inline_executor
    {
      constexpr bool operator==(const inline_executor&) const noexcept
      {
        return true;
      }

      constexpr bool operator!=(const inline_executor&) const noexcept
      {
        return false;
      }

      template<class Function> void execute(Function f) const noexcept
      {
        f();
      }
    };

as, in the case of an unsupported property, the `execution::prefer` call will fall back to an identity operation.

I think the polymorphic executor should be able to simply swap in, so that we could change `do_async_work` to the non-template function:

    void do_async_work(
        polymorphic_executor<
          execution::single,
          execution::oneway,
          execution::outstanding_work> ex,
        std::function<void()> callback)
    {
      if (try_work() == done)
      {
        // Work completed immediately, invoke callback.
        execution::require(ex,
            execution::single,
            execution::oneway,
          ).execute(callback);
      }
      else
      {
        // Perform work in background. Track outstanding work.
        start_background_work(
            execution::prefer(ex,
              execution::outstanding_work),
            callback);
      }
    }

with no change in behaviour or semantics.

Unfortunately, our current single-list-of-supportable-properties design will make this into a compile error if we try to pass it an `inline_executor`. This is because the `polymorphic_executor` template doesn't know that `execution::outstanding_work` is intended for use with `prefer` only. At the point of construction from an `inline_executor` called `ex`, it will try to instantiate implementation templates that perform the ill-formed `execution::require(ex, execution::outstanding_work)`.

**Comment by chriskohlhoff** [comment]
I think we can fix this problem by introducing a `prefer_only` property adapter that turns off `is_requirable` for a specific property. It would be used in the above example as follows:

    void do_async_work(
        polymorphic_executor<
          execution::single,
          execution::oneway,
          prefer_only<execution::outstanding_work>> ex,
        std::function<void()> callback)

Here's an implementation of `prefer_only`:

    template<class InnerProperty>
    struct prefer_only
    {
      InnerProperty property;

      static constexpr bool is_requirable = false;
      static constexpr bool is_preferable = InnerProperty::is_preferable;

      using polymorphic_query_result_type =
        typename InnerProperty::polymorphic_query_result_type;

      template<class Executor>
        static constexpr bool is_supportable =
          InnerProperty::template is_supportable<Executor>
            && execution::can_query_v<Executor, prefer_only<InnerProperty>>;

      template<class Executor>
      friend auto prefer(Executor ex, const prefer_only& p)
        noexcept(noexcept(execution::prefer(ex, std::declval<const InnerProperty>())))
          -> decltype(execution::prefer(ex, std::declval<const InnerProperty>()))
      {
        return execution::prefer(std::move(ex), p.property);
      }

      template<class Executor>
      friend constexpr auto query(const Executor& ex, const prefer_only& p)
        noexcept(noexcept(execution::query(ex, std::declval<const InnerProperty>())))
        -> decltype(execution::query(ex, std::declval<const InnerProperty>()))
      {
        return execution::query(ex, p.property);
      }
    };

**Comment by jaredhoberock** [comment]
I think we would want `prefer_only` only to narrow contracts. For example, I assume we would ban `prefer_only` from being composed with `require`-only properties such as `oneway`?

On that note, there's no analogous use case for a `require_only` adaptor, right?

**Comment by chriskohlhoff** [comment]
> If I understand this proposal correctly, prefer_only sort of hints to polymorphic_executor how the list of properties are expected to be used once instantiated. Mechanically, it indicates to polymorphic_executor which implementations of .require() it should instantiate.

Yep. The polymorphic_executor would use the `is_requirable` attribute to determine which properties need `require` instantiations. So really `prefer_only` simply sets `is_requirable` to false, "hides" any `require` overloads, and otherwise forwards everything else to the inner property.

This means that if you use `prefer_only` with a require-only property you will end up something that is neither requirable nor preferable.

> On that note, there's no analogous use case for a require_only adaptor, right?

I can't think of one offhand. Should probably ponder it further though because it's an obvious question that we may be asked.
