### ISSUE TITLE
Chaining .then and stickiness of executors

### ISSUE THREAD

**Issue by LeeHowes** [executors/executors#35]
In the case of code like:
f.then(e, f1).then(f2);

What executor does f2 run on? f's, or on e?

**Comment by ccmysen** [comment]
Is there a recommendation on this?
I think as a user my default assumption would be that f2 executes on e (you're chaining on the last future). A reasonable alternative would be that it behaves just like future today (the thread of execution is not defined).

A recommended patter here would be to be explicit in your code.
I wonder though if we need a way to introspect on the executor associated with the future.

**Comment by LeeHowes** [comment]
We would prefer it to be as explicit as possible. We have seen a lot of problems of having continuations run on the wrong thread accidentally. Saying it runs on e does make sense but if that is the case then we need to say that modifying the executor of a change switches the rest of the chain to use that executor.

Introspecting on the executor isn't enough if there is a chance that, if the future is already satisfied, then the continuation will run on the current thread. This is what we really want to avoid happening.

**Comment by jaredhoberock** [comment]
@LeeHowes since P0443 no longer defines an interaction between `.then()` and executors, can we close this issue?

**Comment by LeeHowes** [comment]
Yes indeed.
