### ISSUE TITLE
executor(executor<OtherSupportableProperties...> e) constructor might be dangerous

### ISSUE THREAD

**Issue by chriskohlhoff** [executors/executors#353]
Because it is currently specified with:

> *Remarks:* This function shall not participate in overload resolution unless:
> * `CONTAINS_PROPERTY(p, OtherSupportableProperties)` , where `p` is each property in `SupportableProperties...`.

if the conversion is not acceptable then it falls back to using the following constructor:

    template<class Executor> executor(Executor e);

Possible fixes:

* Don't use SFINAE but instead static assert in the constructor.

Or

* Add an extra, deleted constructor to catch the other non-converting case. (This keeps the well-formedness detectable.)

**Comment by AerialMantis** [comment]
Yes, you're right, I noticed this when I was writing the wording for this but I forgot to follow up on it. My thinking at the time was the second idea you suggested of having the fall back constructor be deleted. I feel that approach would align better with concepts in the future.
