### ISSUE TITLE
Typo at executor::query()?

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#358]
Here's `executor::query()`'s wording:

> ```
> template <class Property>
> executor query(Property p) const;
> ```
> Remarks: This function shall not participate in overload resolution unless: `CONTAINS_PROPERTY(Property, SupportableProperties)`.
> 
> Effects: Performs `execution::query(e, p)`, where `e` is the target object of `*this`.
> 
> Returns: `static_cast<Property::polymorphic_query_result_type>(e.query(p))`.

Shouldn't the return type of `executor::query` be `Property::polymorphic_query_result_type`?

**Comment by jaredhoberock** [comment]
Additionally, it seems like the Remarks clause should be extended to say that `query()` doesn't participate in overload resolution unless the type `Property::polymorphic_query_result_type` exists. Otherwise, the call will just be ill-formed.

**Comment by chriskohlhoff** [comment]
> Additionally, it seems like the Remarks clause should be extended to say that query() doesn't participate in overload resolution unless the type Property::polymorphic_query_result_type exists. Otherwise, the call will just be ill-formed.

Since all properties are supposed to be queryable, the lack of `Property::polymorphic_query_result_type` should probably trigger an error at the point where `executor<..., Property, ...>` is instantiated, i.e. tell the user that the property isn't compatible with the polymorphic wrapper at all.

**Comment by jaredhoberock** [comment]
Should be fixed in R6.
