### ISSUE TITLE
Paper should describe the interaction between executors and when_all()

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#37]
The goal of this paper is to describe the interoperation between executors and standard/TS interfaces which create execution agents. Since `when_all()` is one of these interfaces, this paper should describe how it composes with executors.

**Comment by fraggamuffin** [comment]
If we do, then we would also include when_any()?

**Comment by jaredhoberock** [comment]
Here's a little bit more detail about a way to handle `when_al()`. Basically the idea would be to generalize `then_execute()` to handle a variadic number of futures:

    template<class Executor, class Function, class... Futures>
    future<see-below> when_all_execute(Executor& exec, Function&& f, Futures&&... predecessors);

The idea is that the following invocation would occur when all of the futures are ready:

   auto result = f(args...);

Here, `args...` corresponds to the non-`void` values of `predecessors...`. If `result` is not `void`, it is returned via `when_all_execute()`'s result future.

Because it is a generalization, `when_all_execute()` would make `then_execute()` superfluous, because `then_execute()` would just be a synonym for `when_all_execute()` with a single predecessor future.

`when_all(exec, futures...)` would map onto `execution::when_all_execute(exec, f, futures...)`. The function `f` would just do something simple like call `make_tuple()` on its arguments.

There's also the form of `when_all()` which takes a dynamic number of futures. Not sure what is the best way to handle that yet.

It seems possible to handle `when_any()` in a similar way to `when_all()`: we could introduce `execution::when_any_execute()`. The user's function could receive a `std::any` and an index indicating which predecessor future it received. However, I worry a bit about proliferating executor customization points. It may be possible to implement `when_any()` without mapping it directly onto a customization point created especially for it.

**Comment by ccmysen** [comment]
so, the default when_any and when_all don't require the executor to natively support anything, no?
This seems like an optimization that we have a single-executor form of when_all which can potentially make the optimization faster. is that the point of having a special customization point for this (that there's some native implementation that is more efficient than the naive solution)?

**Comment by jaredhoberock** [comment]
We've decided that the interaction between executors and control structures such as `when_any` & `when_all` need to be explored in separate papers.
