### ISSUE TITLE
Consider order-invariance for SupportableProperties... list

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#370]
Feedback from SG1 is that they would like `executor<P1,P2,P3>` to be interoperable with `executor<P3,P2,P1>` etc. It seems like we should get some degree of interoperability already through the converting constructor. However, there might be a way to make these two types identical through some sort of alias. It's not clear to me whether that would require imposing a total order on all property types, though.

**Comment by AerialMantis** [comment]
For interoperating the narrowing constructor we have should cover this already as the requirement for being considered in overload resolution is still met for a matching set of properties.

I'm not sure if we could enforce an ordering of properties in the polymorphic executor type itself, though if we were to have a total ordering of properties perhaps we could introduce an alias to an equivalent canonical type which a polymorphic executor could be converted to. This alias could then be used when declaring a polymorphic executor:

```
executor<directionality.twoway, cardinality.bulk, mapping.thread>::canonical_t executor_;
```

Then initialisation and assignment from another executor or polymorphic executor (even if the property order if not the same) would implicitly convert to the canonical type.

This could also be useful for removing duplicate properties.
