### ISSUE TITLE
Consider ignored_factory type or similar

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#371]
Some folks from AMD expressed a desire for a standard token type that would indicated that the result of a shared factory should be ignored. The idea is that executor types could provide specializations for their bulk execution functions which would avoid invoking such factories and arranging storage for their results.

**Comment by jaredhoberock** [comment]
An alternative suggestion was to introduce bulk execution functions with signatures that do not include the factory parameters. I think that would be a mistake because it would complicate the execution function interface and introduce further design churn. However, introducing some standard
type serving as a hint seems like an OK extension to me because there’s not currently a way to detect when a user-defined function has no observable  side effects.

**Comment by chriskohlhoff** [comment]
Couldn't an implementor simply test `std::is_empty_v<std::invoke_result_t<SharedFactory>>` instead of having a standard token type?

**Comment by jaredhoberock** [comment]
Yes, an implementor could detect that case and avoid allocating storage for the result. There's still an argument that the factory invocation could have observable side effects even if the result it returns is an empty type and that those side effects should be faithfully preserved. On the other hand, we could simply decide any such effects are not worth it and that executors are free to abstain from invoking such factories.

If we don't already do so, maybe we could word the bulk execution function semantics in such a way that the factories are invoked no more than once?

**Comment by jaredhoberock** [comment]
To be concrete, I think we could completely address this concern by introducing this wording into e.g. bulk_execute’s operational semantics:


>Invokes sf() __at most once__ on an unspecified execution agent to produce the value s. Creates a group of execution agents of shape n which invokes DECAY_COPY( std::forward<F>(f))(i, s) at most once for each value of i in the range [0,n), with the call to DECAY_COPY being evaluated in the thread that called bulk_execute. 
>
>May block pending completion of one or more calls to DECAY_COPY( std::forward<F>(f))(i, s)

We may wish to do this for all factories simply for consistency with the way other functions in the interface are invoked.
