### ISSUE TITLE
.get_promise() on all executors

### ISSUE THREAD

**Issue by LeeHowes** [executors/executors#378]
I would like to propose an addition.

When thinking about how to implement .via to convert future types I ended up using then_execute to achieve this. This makes sense because then_execute defines a future type to return.

In my initial implementation I ended up exposing a public set_callback method on the future, with strict rules, but that seems clunky for two reasons:
1) It ends up being on SemiFuture too
2) It ends up seeming to duplicate .then

We were thinking about how else to do this, and concluded that putting the workload on the executor made more sense.

I propose that we add to the executor concept a method:
template<class T> get_promise();

That returns an implementation of a promise concept (TBD) that has understanding of this executor.

The promise will have a get_future method, and that future can be passed into the executors then_execute method, which allows then_execute to restrict itself to certain future types, and to be optimally implemented in terms of those.

The promise/future pair here need not be the same future type then_execute returns, or indeed the future type of the executor. All it is is a future that:
1) Completes when the promise is set.
2) Is valid as a source future for then_execute.

This idea has value outside of the future definition. Specifically, we can do something like this:

GPUExecutor e;
auto p = e.get_promise<void>();
auto f = p.get_future();

THEN:
f.bulk_then(thing)..bulk_then(thing).bulk_then(thing);

OR:
auto f2 = e.then_execute(thing, f);
auto f3 = e.then_execute(thing, f2);
auto f4 = e.then_execute(thing, f3);

In either case we can greedily build, say, a GPU work queue here. Then we kick that off on the device with:
p.set_value();

This is cleaner than starting such a work chain using twoway_execute, because it is even more explicit in saying that the work is delayed. At the same time, it enables a completely optimal underlying synchronization for that promise/future pair.

It means that .via on a future/semifuture is implemented as either an optimal solution if the future is already paired with the executor, or:
auto p = e.get_promise<Type>();
auto f = p.get_future();
this->set_callback([](Type&& v){p.set_value(std::move(v);});
return e.then_execute(Passthrough{}, f);

and of course, for an executor where the future returned by p.get_future is the same as that returned by then_execute, specialisation for Passthrough trivially returned the same future. It just allows the executor to optimise by having a shared-state future for communicating with other executors, and a primary non-shared-state future for internal chaining work.

**Comment by jaredhoberock** [comment]
One problem for GPU executors in particular is that a promise model isn't really the right fit. GPU "promises" are automatically satisfied by the hardware, without any software participation. I'm concerned that introducing a requirement for a promise type would simply result in overhead.

I think it may be possible to satisfy your second use case without requiring a promise. In our implementation within Agency, `make_ready_future` may be customized by the executor. The equivalent way to express your chaining example could be something like this:

```
GPUExecutor e;
auto f = e.make_ready_future();

THEN:
f.bulk_then(thing)..bulk_then(thing).bulk_then(thing);

OR:
auto f2 = e.then_execute(thing, f);
auto f3 = e.then_execute(thing, f2);
auto f4 = e.then_execute(thing, f3);

GPUExecutor e;
auto p = e.get_promise();
auto f = p.get_future();

THEN:
f.bulk_then(thing)..bulk_then(thing).bulk_then(thing);

OR:
auto f2 = e.then_execute(thing, f);
auto f3 = e.then_execute(thing, f2);
auto f4 = e.then_execute(thing, f3);
```

If there's a way to define requirements for `Future` without needing to also introduce promises, I'd be for that.

> In my initial implementation I ended up exposing a public set_callback method on the future, with strict rules, but that seems clunky for two reasons:
> 
> It ends up being on SemiFuture too
> It ends up seeming to duplicate .then

Do you have additional details on this attempt? What exactly was `set_callback`'s role?

**Comment by LeeHowes** [comment]
Of course we don't want promises as a requirement for GPU execution, for the reasons you mention. We have then_execute to do future->future dependencies on the GPU. This is why I was careful to say in my proposal that e.get_promise().get_future() need not return the same type as then_execute.

The point is that at some point non-GPU work has to become GPU work. We currently have no way to say that we want to build a queue of GPU work, and trigger it on some CPU completion. 

Make_ready_future is no good either, because it returns a future that is ready. If we add the CPU work to your example we have a problem:

```
CPUExecutor c;
auto cf = c.make_ready_future();
cf = cf.then(do some long running thing);

// How do we here chain onto the GPU executor? We can maybe do:

GPUExecutor e;
cf.then([](auto v){return e.twoway_execute(...);};
```

but I don't know how to implement that in the CPU future type. I can't call make_ready_future, because the work is not ready yet.

So what I want to do here is connect the two. My original proposal was to have then_execute hide a promise-type construction internally, and call .then on cf. This means that cf.via(e) can't return a GPU future easily, though.

So the alternative idea was to just allow the GPU executor to provide whatever the best primitive it can for being notified by the CPU to run work on the GPU - and that we expose as a promise/future pair. This might also be an excellent use case for a future that has no .get method - it means nothing, it is only useful for chaining work.

**Comment by jaredhoberock** [comment]
Thanks for the explanation. I understood the suggestion for a promise type differently, i.e. as a channel for an executor to communicate that some internally-created work has completed. Now I understand that it is meant for the opposite direction: to communicate to the executor that some externally-created work has completed.

It kind of seems like the fundamental idea here is a need for a channel for signaling the completion of a future and by construction that channel needs to be outside of an executor's execution function. Is that a fair summary?

**Comment by LeeHowes** [comment]
I think that's it. 

We can always tie things the other way in the current design - a given executor always could be enqueued a task that satisfies some "promise" for some destination future - whatever the definition of promise is in that case. It could simply be a lazy enqueue to a one-way executor, with no explicit promise. So to satisfy some arbitrary transition from e to e2:
e.execute([](){e2.execute(foo);});

The reverse is not possible unless we expect all enqueue to be lazy, which defeats the object of then_execute, I think. So providing a channel by which an executor can wait on some action, with a consistent interface for some producer to satisfy that action, I think is the gap in the current specification.

**Comment by LeeHowes** [comment]
During the call on 2018-04-07 we prefer get_promise to changing two_way. Chris K has good use cases for twoway_execute. Better to have this as an additional parameter (that future.then might always require).

Chris also has an idea for an adapter approach. He will investigate this.

He also pointed out that we have to be careful about the polymorphic executor. Although I'm not sure this is a bigger problem compared with how then_execute works.

Lee will look into wording for get_promise.

**Comment by LeeHowes** [comment]
I've drafted get_promise text in a branch:
https://github.com/executors/executors/tree/get_promise

This is based around using std::variant<T, std::exception_ptr> as a way of handling errors and of describing the promise. That text should obviously be specified based on what we agree in https://github.com/executors/executors/issues/382

**Comment by chriskohlhoff** [comment]
Without commenting on the merits of the change itself (still trying to decide what I think on that), I will note that the obvious, and idiomatically correct English, name for this function is not `get_promise`, but `make_promise`. :)
