### ISSUE TITLE
Can we also bifurcate on host-based and remote-based (is that event now?) with bulk_executor()?

### ISSUE THREAD

**Issue by fraggamuffin** [executors/executors#38]
First, I thought there was originally a host-based and remote. After Chris K's merge, is remote-based now called event executor?
The reason is that in SYCL, we need to differentiate remote and hosted bulk_executor because of incompatible FPG between CPU and GPU. The current C++17 CD specifies parallel forward progress guarantees for par and weakly FPG for par_unseq. The FPG for par would not work on GPU devices. But if we have remote then these can have different FPGs.

**Comment by jaredhoberock** [comment]
Can you give a little bit more detail about your use case and also what forward progress guarantees does your use case require?

**Comment by chriskohlhoff** [comment]
N.B. EventExecutor is a refinement of HostBasedOneWayExecutor, so not remote. The remote-capable one is plain OneWayExecutor.

**Comment by jaredhoberock** [comment]
Since `HostBased` no longer exists in the design, we can close this.
