### ISSUE TITLE
Exception processing in then_executor

### ISSUE THREAD

**Issue by LeeHowes** [executors/executors#382]
The proposal covers what to do if a function passed to one of the various .execute family throws. The text is written with the assumption that the future is capable of carrying an exception internally, which is consistent with everyone's expectations, I think.

It does not say what to do for then_execute(task, f) if f carries an exception. We have no way to pass a special exception-handling task, and no agreed parameter that would allow me to write a task and pass it in, correctly packing the value and exception.

We have largely agreed, I think, that we do not want to pass a future to the continuation - it's clunky, it is not really accurate, it might confuse typing if that future and the future returned by the executor do not match, and it might even be inefficient to execute if we have to produce a future that we can safely attach a continuation to.

We have in the past discussed using std::expected. We do not have std::expected in the standard, much to many peoples disappointment.

During Wednesday's F2F it was suggested that we use std::variant<T, std::exception_ptr> as the parameter to the callback passed to then_execute (not to .then on the future, but the extra syntax in the executor API was deemed ok, as the Future would be handling the unpacking/rethrow). This nicely reuses a standard primitive, and allow us to easily define the future-level API in terms of std::visit.

Jared: you had a concern on https://github.com/executors/futures/issues/7 about GPU-compilability of std::expected. I presume that the same would apply to std::variant. Correct me if I'm wrong.

Any strong opinions? Another option would be that we define a concept, or a special type, maybe along the lines of folly::Try, but that we know we can implement fairly simply for all agents.

**Comment by LeeHowes** [comment]
A possible alternative design is that we require this parameter to be specifically one of: std::always_ready_future<T, current_executor_t> or std::always_ready_semi_future<T>.

That way we know it always carries the state internally and can guarantee to keep the cost down. In effect, this is a Try type - as a specific type we can flesh out its API with:
hasValue();
hasException();
value();
exception();
and of course:
get();

For the Future version we'd also have .then and work would be enqueued onto the executor (the same executor as the callback was satisfied on).

Further, it wraps the executor so we can get access to that with .get_executor, rather than having an optional Executor& parameter to the callback as I have proposed before.

**Comment by LeeHowes** [comment]
Or, indeed, to define an always_ready_future concept that optionally supports exceptions and is exported by the executor.

A Promise can be defined as a Callable(Executor::always_ready_future_t<T, Ex>) where Ex might be void (and therefore be a SemiFuture). The parameter of the continuation can be defined similarly, thereby giving consistency between a promise concept and the callback definition.

**Comment by jaredhoberock** [comment]
> It does not say what to do for then_execute(task, f) if f carries an exception. We have no way to pass a special exception-handling task, and no agreed parameter that would allow me to write a task and pass it in, correctly packing the value and exception.

If `f` is exceptional, one option would be to simply forward the exception along to the future returned by `then_execute`, and simply bypass executing `task` at all.

> Jared: you had a concern on executors/futures#7 about GPU-compilability of std::expected. I presume that the same would apply to std::variant. Correct me if I'm wrong.

Yes, I'd rather we didn't nominate a particular concrete type like `std::expected` or `std::variant` as a channel for communicating exceptions, for the reasons I mentioned on that other issue.

Have we explored a variant of `then_execute` which would take the task, future, and a another user-defined function which would be executed instead of the task upon error? That kind of alternative would receive both the user function and a user error handling function together:

    auto f2 = ex.try_then_execute(task, f1, call_this_on_error);

Then there's another alternative that would separate the function from the error handler:

    auto f2 = ex.then_execute(task, f1);
    auto f3 = ex.on_error(call_this_on_error);

Or this alternative could be a member of the future:

    auto f2 = ex.then_execute(task, f1).on_error(call_this_on_error);

These solutions are similar to how other languages (e.g. Javascript) deal with this problem. We should at least consider them, and provide reasons why we disqualified them, if that's what we end up doing.

**Comment by LeeHowes** [comment]
I would question that being a good design, because it would be easier to implement two functions on one than one on two. In our code we'd prefer to be using expected types and it would be hard to cleanly build that on executors that do not support it directly - it is already a serious source of bugs that users double move into the pair of functions passed to .then and .onError on futures, such that we try to get our developers to use folly::Try as a continuation parameter and do it in a single callback unless there is a good reason not to. Splitting the function in the implementation would probably mean that we have to heap allocate the real callback and pass two separate ones to the executor, both of which call it the shared one, so that we don't have to attempt to split the callback state. 

We can definitely implement two functions on the future, but the executor still has to be able to execute the error handler. Or at least, executors in general have to - it is perfectly ok if a given executor is unable to do so. Not being able to process (as opposed to passing on) exceptions at all would just mean we have to implement everything in terms of one-way executors, which seems unfortunate.

At the moment I lean towards the idea of an always_ready_future concept. I'm investigating that a bit further today. That way we can optimise the underlying storage of the data as much as we like for a given executor.

**Comment by jaredhoberock** [comment]
> In our code we'd prefer to be using expected types and it would be hard to cleanly build that on executors that do not support it directly 

This should be possible to build on top of P0443 already, right? It is possible to return expected types wrapped inside futures from execution functions because from the executor's perspective, `std::expected` is just another value type. Is there something missing that prevents this approach?

**Comment by LeeHowes** [comment]
That is true, it just means that every future<T> has to wrap (or at least to be able to unwrap) an future<expected<T, E>> to interact with executors. It also takes control away from the executor on what types you are able to compile in that it'd end up with me putting expected types through all executors from a whole class of futures, which you may not be able to compile on the GPU. We lose a potential compatible interaction.

**Comment by jaredhoberock** [comment]
Just as an aside, a fancy future adaptor that takes some other future type that returns `T` and wraps it such that it the new result type is `std::expected<T>` might be an interesting archetypical future example.

**Comment by jaredhoberock** [comment]
I wonder if a useful way to approach this is to keep the `then_execute` behavior simple (i.e., just forward along any predecessor exception and skip the user task), but introduce some more flexible user-facing control structures or adaptations on top for exception/error propagation. In this approach `.then()` would be an example of a control structure, but it needn't be the only one for chaining continuations. For example, the function of one of these control structures could be to adapt an exceptional future into an expected-returning future which never has an exceptional state. The point of all of this is that executors beneath this stack can be oblivious to all the stuff happening on top.

**Comment by jaredhoberock** [comment]
> The conversion you're suggesting might work in theory, but I think there are a lot of uncomfortable problems you'll run into. The first that comes to mind for me is that there's no straightforward way for an executor to use an existing future type like std::experimental::future, since I don't see how you'd do the conversion from std::experimental::future<T> to std::experimental::future<expected<T>> without enqueuing an additional operation (am I missing something here?).

I came to a similar conclusion myself after thinking it through over the weekend. It seems like there are a lot of use cases for converting a future into another future of a related type, but in general they come at the expense of burning an execution agent.

I still favor something like this basic approach of keeping the `then_execute` behavior simple and as close to R6 as possible. At the moment, the [idea](https://github.com/executors/executors/issues/383#issuecomment-381707976) I outlined in #383 is my current favorite.

There are a few things I favor about this idea:

1. It doesn't require new types or concepts
2. There are no requirements on the type of the incoming predecessor
3. The predecessor argument is passed to the user function consistently with the result and shared parameters (they are all lvalue references)
4. The protocol can be adapted by control structures layered on top to present users with different UIs focused on conveniences targeted at different error handling use cases.

I share [Lee's concern](https://github.com/executors/executors/issues/383#issuecomment-381729124) about the challenge of dealing with user callbacks with `auto` parameters, but it doesn't seem insurmountable.

**Comment by LeeHowes** [comment]
auto may work. One callback has to take exception_ptr and should bind better than the other being auto.

Or we name them rather than use operator(), it's all hidden under the code anyway, and make the exception one optional.

As I point out in the other task, it circles back to the original proposal I made at the F2F, so I think that is something we could agree to, with some tuning of the finer points. It still needs a concept to define that thing that is passed in, and I don't think it is simpler in practice than the ready_future concept, just slightly different and working from the callee point of view rather than the parameter point of view.

**Comment by LeeHowes** [comment]
Posts here have become inconsistent. I just posted in #383 building on Jared's post. It applies to both versions of the function.
