### ISSUE TITLE
Forward progress requirements of non-blocking executors

### ISSUE THREAD

**Issue by LeeHowes** [executors/executors#385]
We need to be clear precisely what the minimum is and what non-blocking means in this case.

It may not necessarily mean lock-free. Atomics need not be lock-free, but a promise could implement set_value as a state machine that can only move forward:
```
In set_value:
  Store result and set atomic flag
If in initial state:
  Set state to has_result; Break
If has callback:
  Set state to armed
  Call callback with result
```

That is only locking in the sense that the atomic operations may lock.

Actual lock-freedom may or may not be necessary then, only that even in the presence of a lock, there is a guarantee that the lock will be released to allow the algorithm as a whole to make progress.

Is there wording we can write that guarantees this level of progress, such that we can assume that calling the various execution, continuation attaching and non-blocking modification operations on futures and executors are safe to call from weak agents.

As an explicit example, if I do:
`auto val = std::this_thread::get(weakAgentFuture.via(threadExecutor));`

I am using the current thread to block on the future. That is safe, it's a thread after all. I need to know that the weak agent (a GPU thread, a fiber, whatever it is) can enqueue the a task onto that threadExecutor safely, even while it would in itself not be safe to execute a blocking operation on.

**Comment by chriskohlhoff** [comment]
By "non-blocking" are you referring to the blocking_t property? If so, the blocking property has nothing to do with lock-free. It is simply whether the execution function blocks pending completion of the submitted function object (and so may introduce a precondition for deadlock). Executor implementations are free to use either locking or lock-free mechanisms to implement their queueing. We don't currently have a property that describes the behaviour of the queueing mechanism itself.

**Comment by LeeHowes** [comment]
You are correct, of course. What I want to get to here is what minimum wording we should clarify that with so that we understand the constraints on enqueue/promise satisfaction from weak agents.

For example, if I want to enqueue from a fiber I don't mind taking a mutex on an internal data structure. Lock-freedom is not really the property I need - more a guarantee that on entry it will complete as if concurrent. I do mind if something inside that enqueue actually switches my fiber out. Maybe that is a reasonable implication of the blocking property, but maybe not as that might be intended to be a temporary context switch - the unfortunate result might be blocking the other fiber that needs to satisfy this one to make progress.

So I'm unsure if either the current wording, or that plus a lock-free query, is enough. It can probably be clarified later either way and possibly shouldn't block this effort.
