### ISSUE TITLE
Consider improving wording of bulk_guarantee properties

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#401]
As Dean and Billy observe via a reflector discussion, the term "vectorized" is not defined by the IS.

P0443 uses the term to describe the meaning of `bulk_guarantee.unsequenced`:

> Execution agents within the same bulk execution may be parallelized and vectorized.

It might be clearer just to say something like:

> Execution agents within the same bulk execution may **not be sequenced**.

**Comment by jaredhoberock** [comment]
A similar improvement could be made to describe the meaning of `bulk_guarantee.sequenced`, which currently says:

> Execution agents within the same bulk execution may not be parallelized.

Instead of negatively describing what agents may not do, we could say positively what they are required to do:

> Execution agents within the same bulk execution **execute in sequential order**.

**Comment by AerialMantis** [comment]
This change sounds good to me.
