### ISSUE TITLE
What is the intent of `F&&` in executor requirements, rvalue reference or forwarding reference?

### ISSUE THREAD

**Issue by brycelelbach** [executors/executors#406]
In each of the different executor requirements in P0443, there is a paragraph similar to this one from the `OneWayExecutor` requirements (emphasize mine):

> In the Table below, `x` denotes a (possibly `const`) executor object of type `X` and **`f` denotes a function object of type `F&&` callable as `DECAY_COPY(std::forward<F>(f))()`** and where `decay_t<F>` satisfies the `MoveConstructible` requirements.

What is the intention of `F&&` - do we mean for this to be an rvalue reference or a forwarding reference? Presumably we intend this to be a forwarding reference, given that we have `std::forward<F>(f)` in the `DECAY_COPY` expression.

The phrasing "`f` denotes a function object of type `F&&`" is, in general a bit odd. Usually when we talk about placeholder types in type requirements in the standard, we talk about *values* (of a particular value category) of a certain type. For example:

* http://eel.is/c++draft/iterator.requirements#general-14
* http://eel.is/c++draft/containers#container.requirements.general-4.sentence-1

If someone can confirm the intention here (forwarding reference), I will try to clarify the wording here and send a PR.

**Comment by jaredhoberock** [comment]
Yes, they are forwarding references.
