### ISSUE TITLE
How do executors deal with asynchronous system errors and allow users to customize that handling? AKA All execution functions should take receivers (Futures Ask 3)

### ISSUE THREAD

**Issue by brycelelbach** [executors/executors#411]
Today, one-way `execute` (and two-way `twoway_execute`) just require simple C++ callables (lambdas, etc):

```
// Before (P0443 and P1054 today):
// `execute` takes:
struct VoidCallable {
  void operator()();
};
// `twoway_execute` takes:
struct Callable {
  U operator()();
};
// `then_execute` takes:
struct FutureContinuation {
  // At least one of these is required (thus it will be satisfied by a callable):
  U operator()(T value);
  U operator()(exception_arg_t, std::exception_ptr error);
};
```

P1055 suggests that execution functions should take receivers, including one-way `execute`, the only execution function in P1055:

```
// After:
// `execute` takes:
struct VoidNoneReceiver {
  // At least one of these is required (satisfied by `Callable`s):
  void operator()();
  void operator()(exception_arg_t, std::exception_ptr error);
};
// `twoway_execute` takes:
struct NoneReceiver /* AKA a `Callable` */ {
  // At least one of these is required (satisfied by `Callable`s):
  U operator()();
  U operator()(exception_arg_t, std::exception_ptr error);
};
// `then_execute` takes:
struct Receiver {
  // At least one of these is required (satisfied by `Callable`s):
  U operator()(T value);
  U operator()(exception_arg_t, std::exception_ptr error);
};
```

This change arises from the question of what executors should do when an asynchronous system error occurs.

By asynchronous system error, I mean an error that occurs after the one-way execution function has returned that prevents the executor from creating the execution agent and/or invoking the work item in it. For example, shutdown or resource exhaustion could lead to this class of error.

There are currently no requirements on how an executor would report such an error. Presumably, most executors would follow the path of the ISO C++ standard and do something like `std::terminate` in this case.

There are a few fundamental questions here:
- Q: Do we want to provide a mechanism (not necessarily this one) for allowing users to provide a handler for this type of error?
  - A: Personally, yes, I think we should provide a solution for this.
- Q: If so, do we want to do this in version 1 of executors?
  - A: I feel that this mechanism is nice to have, but I'm not convinced it's essential for version 1.
- Q: Do we want to handle the two different asynchronous error channels in executors, asynchronous errors arising from *user code* that a work item is dependent on and asynchronous errors arising from *system erros* preventing the launch of a work item, using the same mechanism?
  - A: No, I would prefer to either have (a) two separate hooks (one for errors from dependencies, one for system errors) or (less favorable to me) (b) one hook, but it provides you a way to distinguish between the two code paths at compile time (for example, the error method could take a second parameter which is a tag type indicating the source of the error). 
- Q: Do we care if the error method of a `FutureContinuation` is called from an unspecified thread of execution instead of on an execution agent created for it by the executor it was enqueued to? What are the downsides to making this unspecified?
  - A: I think we probably want to avoid features that make it unspecified on which thread of execution user code runs whenever possible. We've had a bad experiences with this historically (futures in the Concurrency TS v1, for example).
- Q: If a user provides an error handler for asynchronous system errors, is the executor required to use it?
  - A: I feel very strongly that if the user provides a handler, it must be used.

[This was discussed during the 2018-07-13 executors phone call](https://github.com/executors/futures/blob/master/notes/meetings/2018_07_13__executors__weekly.md):
- Bryce: P0443 is consistent with the IS; exceptions that escape from a thread of execution lead to `std::terminate`.
- Lee: The example is a non-blocking launch + a shutdown request that arrives before the work is started.
- Chris K: This should be handled through a different channel.
- Chris K: The problem is that the error function is not called in the right execution agent. But for `then_execute`, it will be called in the execution agent. You are using the same channel for two different things.
- Bryce: For `then_execute`, can this be called due to a launch error.
- Bryce: The proposal is that this error method would be used to handle both "system" errors and errors contained in tasks?
- Bryce: This means that error is invoked on an unspecified execution agent. Remember the Concurrency TS v1.
- Jared: Is an executor allowed to throw for synchronous errors? Or does it have to use the error method?
- Bryce: If you don't always use the error method, changes in the implementation of an executor can change the error handling path. I think the error method would always have to be used.
- Lee: Not just about launch errors, also things like shutdown, migration, cancellation, etc.
- Chris K: We want two channels, one for dependency errors, one for system errors.
- **Bryce: Idea - have two channels (or a way to signal error category) on receivers.**
- Lee: What if the preceding task forwarded the error to it's dependency?
- Bryce: Two questions for Jared and Chris K:
  - Should we provide some way of providing an error handling hook for asynchronous system errors?
  - Would you feel differently about this if there was a way to distinguish the error category (system or predecessor)?
- Jared: Could this be done with properties?
- Lee, Kirk: Executors do not have to report system errors with the error method even if it exists.
- Lee, Kirk: This is needed for error propagation if we rebase `then_execute` on `execute`.
- Bryce: So a non- or maybe-blocking executor may choose to, but doesn't have to, report system failures (shutdown, launch failure, etc) that occur after the execution function returns via the receiver's error method?
- Bryce: That makes error handling inconsistency in generic code.

**Related Issues:**

- #412, which deals with the question of where exception propagation should live in the executors software stack.
- #413, which deals with the question of whether the one-way execution function should accept receivers that expect to be passed an executor.
- #414, which deals with how we should spell the value method of work items if this ask and the two above are accepted.

**Comment by LeeHowes** [comment]
Another valid type of asynchronous error is where the executor not been unable to create the agent, but has simply decided not to. We had a recent request along these lines where someone wanted to build an executor that supported QoS guarantees, which we can think of as a means to communicate a timeout on a task. 

Current folly executors do not really have a means to communicate this. However, if a oneway task can take an error callback, then there is a means to do this. It is obviously open to discussion whether the error(TimeoutError) call should have to happen on a created agent, or whether it is ok for it to happen in some unspecified agent, but it should also be clear that creating an agent that let's a task know it has timed out is still a different action from actually running the task - you can still differentiate the resource use from this, not issue network requests for example.

So here we'd have a task that looked, at a minimum, like:
`struct thetask{ void done(); void error(TimeoutError); }`

or potentially exception_ptr if we want to allow throw + catch as a means of handling this and depending on the rest of the conclusion in #412 

It seems to me that there is huge value in having the flexibility to deal with errors asynchronously, and the main downside is in defining where the value and error operations are allowed to run, which is a solvable problem.
