### ISSUE TITLE
Receiver's value method shouldn't be the call operator (Future Ask 6)

### ISSUE THREAD

**Issue by brycelelbach** [executors/executors#414]
This is a consistency matter that will become relevant if adopt #412 (Future Ask 4) and #409 (Future Ask 1).

```
// Before (P0443 and P1054 with Ask 1 and Ask 4):
// `execute` takes:
struct VoidNoneReceiver {
  // BOTH of these are required (NOT satisfied by `Callable`s):
  void operator()();
  void error(exception_arg_t, std::exception_ptr error);
};
// `twoway_execute` takes:
struct NoneReceiver {
  // BOTH of these are required (NOT satisfied by `Callable`s):
  U operator()();
  U error(exception_arg_t, std::exception_ptr error);
};
struct Receiver {
  // BOTH of these are required (NOT satisfied by `Callable`s):
  U operator()(T value);
  U error(exception_arg_t, std::exception_ptr error);
};

// Using P1054-style `on_value`:
exec.execute(on_value([] { /* ... */ });
auto f = exec.twoway_execute(on_value([] { /* ... */ }));
auto g = exec.then_execute(on_value([] { /* ... */ }, pred));


// After (P0443 and P1054 with Ask 1 and Ask 4):
// `execute` takes:
struct VoidNoneReceiver {
  // BOTH of these are required (NOT satisfied by `Callable`s):
  void done();
  void error(exception_arg_t, std::exception_ptr error);
};
// `twoway_execute` takes:
struct NoneReceiver {
  // BOTH of these are required (NOT satisfied by `Callable`s):
  U done();
  U error(exception_arg_t, std::exception_ptr error);
};
// `then_execute` takes:
struct Receiver {
  // BOTH of these are required (NOT satisfied by `Callable`s):
  U value(T value);
  U error(exception_arg_t, std::exception_ptr error);
};
// Using P1054-style `on_value`:
exec.execute(on_value([] { /* ... */ }));
auto f = exec.twoway_execute(on_value([] { /* ... */ }));
auto g = exec.then_execute(on_value([] { /* ... */ }), pred);
```

I'll let @LeeHowes make the case for this.

[This was discussed during the 2018-07-13 executors phone call](https://github.com/executors/futures/blob/master/notes/meetings/2018_07_13__executors__weekly.md):
- Lee: This increases consistency.
- Jared: If both cases are required, I agree. Otherwise, I'd prefer the normal case to just be the call operator

**Related Issues:**

- #411, which deals with the question of how executors should handle asynchronous system errors.
- #412, which deals with the question of where exception propagation should live in the executors software stack.
- #413, which deals with the question of whether the one-way execution function should accept receivers that expect to be passed an executor.

**Action Items:**
- [ ] (@LeeHowes) Advocate for this.

**Comment by LeeHowes** [comment]
1) It's better to be explicit.
2) Both methods should be required, which bring's up Jared's point.
3) When both methods are there, it is just better to be explicit.
4) If we follow the proposal in #411 so we have a way to handle errors, which we should, then the default is actually *not* the value callable, because a one-way executor does not have a value callable.
