### ISSUE TITLE
Inconsistent nested property object names

### ISSUE THREAD

**Issue by griwes** [executors/executors#429]
The contents of the "Nested Property Object Name" columns in the various tables are inconsistent.

* Some of them refer into the property type, like `blocking_t::always`.
* Some of them refer into the property type object, like `blocking_adaptation::disallowed` (which is actually invalid, because `blocking_adaptation` is an object, not a class, namespace, or enumeration, as clang's error message eloquently error out).
* None of them (this is a cheeky point) use the member access syntax, for instance `relationship.fork`.

Both `property_t::nested` and `property.nested` are valid, but the one that isn't used at all - `property.nested` - seems to be the one that is most useful for users; I'd be fine with either of them, though, even if `property_y::nested` loses some educational value.

Thoughts?

**Comment by jaredhoberock** [comment]
My preference would be to use the "pretty" names like `property.nested`, if possible. There might be some reason it isn't, though.

**Comment by griwes** [comment]
Right; my main problem is that some of them are actually invalid expressions, so whichever way we go with this, we should at least make them valid.
