### ISSUE TITLE
Consider all-or-nothing guarantee for bulk_execute

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#432]
`bulk_execute`'s operational semantics include this:

>Shall not propagate any exception thrown by cf or any other function submitted to the executor. [Note: The treatment of exceptions thrown by bulk one-way submitted functions and the forward progress guarantee of the associated execution agent(s) are implementation defined. --end note.]

This language seems to permit the executor to fail via exception in the middle of the submission, having created a partial group of execution agents. The problem is that it's difficult to see how a client could handle that exception without a universal way of communicating which agents were successfully created. 

One option would be to ban `bulk_execute` from creating agents if an exception is thrown. Would that be too restrictive?

**Comment by AerialMantis** [comment]
Hi everyone,

I don’t see this requirement being a problem for heterogeneous executors as most APIs tend to launch all or nothing anyway. But it might be more difficult to make that guarantee on std::thread based executors. For example, you could have a bulk_execute allocating too much thread_local memory and the exception is triggered after earlier execution agents have already launched.

Thanks,

Gordon

________________________________
