### ISSUE TITLE
.then_executor missing from TwoWayExecutor

### ISSUE THREAD

**Issue by chriskohlhoff** [executors/executors#44]

**Comment by ccmysen** [comment]
i'm still mixed on whether we really want to push then_execute in the initial executor paper, it feels a little half-baked to me still and without a concrete future::then proposal with executors it's not so obvious that this is useful to have.

**Comment by jaredhoberock** [comment]
The refactoring of executor concepts resolved this. `.then_execute` is now a requirement for `ThenExecutor`.
