### ISSUE TITLE
P0443 Review: Sender/Receiver: Polls

### ISSUE THREAD

**Issue by atomgalaxy** [executors/executors#497]
Dear Authors,

In today's (June 29th) LEWG meeting, we explored a few issues with the current paper. Some of them require small design changes. The chair felt that having straw polls would unblock the team in making those changes (if welcomed by the authors).

We are asked to come up with poll wording that would be helpful to the authors as guidance and empower you to make the changes you feel would be good for the design.

I'm making this an issue here on GH because I'm hoping it's a way to reach all the authors. I'll fill in the likely suggested polls as the meeting minutes become available.

If you think you have sufficient notes (or ideas) to suggest some, feel free to just put it here.

I will supply these to the Chair before next week's meeting, so the deadline is 6 days from now (July 5th).

Thank you very much,

Your Review Group 2 chair.

**Comment by jaredhoberock** [comment]
Thanks Gašper.

My personal preference would be to create separate issues for each action LEWG decides they want the authors to take as a result of these polls. That way we'll have a paper trail and discussion space for the very fine details.

**Comment by atomgalaxy** [comment]
Hi Jared,

We will, but this thread is to decide which polls the authors would even
consider helpful. After all, they are direction polls, and if their results
are not helpful to the authors, they are useless.

I'll put the ones that I can discern from the minutes in here and we can
debate them. Any other design decisions the authors would like LEWG to
weigh in on are also welcome.

Polling should be designed together, then we can make issues.

Am I making sense?

**Comment by jaredhoberock** [comment]
Yes, it makes sense. My concern with that comment was simply to emphasize that the deliverables from such polls should appear as Github issues which ideally can be resolved via pull request.

**Comment by atomgalaxy** [comment]
Agreed :)
