### ISSUE TITLE
prefer_only example is out of date

### ISSUE THREAD

**Issue by dkolsen-pgi** [executors/executors#498]
In P0443R13, section 2.4.2 "Struct `prefer_only`", the code in the example is out of date.  I think the example is sound, it just uses the old name of something that has been renamed, and uses a couple properties that have been removed from the paper.

The necessary changes are:
  * Change `executor` to `any_executor`.
  * Delete references to obsolete properties `execution::single` and `execution::oneway`.
  * With those two properties gone, some calls to `std::require` now have no properties to require.  Those calls to `std::require` should be removed.

**Comment by jaredhoberock** [comment]
Fixed in resolution to #486
