### ISSUE TITLE
ExecutorWorkTracker semantics and effects not well defined.

### ISSUE THREAD

**Issue by ccmysen** [executors/executors#51]
The current paper is not particularly clear on the effects of calls to on_work_started and on_work_finished when they are provided. 

The work guard indicates that it effectively behaves like a lock on the executor but there's not a guarantee anywhere that the context will obey such a lock, so it's not so clear anywhere what benefit you get by calling on_work_started (given there's no indication as to the effect).

**Comment by jaredhoberock** [comment]
`ExecutorWorkTracker` no longer exists in P0443, so closing.
