### ISSUE TITLE
Remove exception_list in Task block

### ISSUE THREAD

**Issue by fraggamuffin** [executors/executors#62]
Change below to Terminate and resume, as exception_list has been removed from Standard and while exeption_lists still exists in the TS2, we should probably think about keeping with C++17?
Throws: exception_list, as specified in version two of the Paralellism TS.

**Comment by fraggamuffin** [comment]
But I can see why you might leave this as is as you are just following the task block definition in TS2.

**Comment by mjgarland** [comment]
I think that for now, we should just follow the existing definition of task blocks in the Parallelism TS2.  If we want to change the behavior of task block w.r.t. exception_list, it would be best to do it all at once.

**Comment by mjgarland** [comment]
This should probably be the topic of a separate paper.
