### ISSUE TITLE
Fix forward progress wording

### ISSUE THREAD

**Issue by mjgarland** [executors/executors#82]
The forward progress semantics in the standard use the concept of "boost blocking" to specify the correct progress guarantees for the weaker forms of forward progress.  The current wording in the paper ignores this.  We should rectify this to make sure that the forward progress wording in the paper is correct.

**Comment by jaredhoberock** [comment]
The consensus we arrived at in Albuquerque is that for `oneway` executors, we introduce some language indicating that some entity, aside from the `oneway` executor, is responsible for guaranteeing app-level forward progress. That wording could use the term boost-blocking.

**Comment by jaredhoberock** [comment]
From February 2 phone call:

1. change the "polarity" of statements regarding blocking in the requirements of the execution functions
2. enhance Future requirements to include boost-blocking
3. enhance the static_thread_pool to include boost-blocking
  3.1 clarify the pre-synopsis note
  3.2 add a paragraph before the section named Types explaining that threads in the pool boost-block the functions/tasks they execute
4. enhance the notes in the operational semantics of .execute() & .bulk_execute()
  4.1 e.g. "The treatment of exceptions thrown by one-way submitted functions and forward progress guarantees are specific to the concrete executor type."
