### ISSUE TITLE
Generalising blocking behaviour 

### ISSUE THREAD

**Issue by LeeHowes** [executors/executors#93]
Currently NonBlocking adds the defer and post functions, which we assume do not block. I understand that execute may still block. This is ok because code could limit itself to NonBlocking and not call execute.

However, it is not clear from the current document if .then can block, or if calling the continuation can block.

So, specifically, if I call .then on an already satisfied future, can the continuation be processed inline or not? I think this needs to be controllable.

Similarly if I add a continuation to a future and then the task behind the future runs and completes the future, can it immediately call the continuation? This is not clear, and there are many situations where it should not.

Clearly this could also be a property of whether an executor is passed to .then, but even if not should .then assume that a continuation be launched on the same executor as the future's task, and at that point the same question applies.

**Comment by jaredhoberock** [comment]
P0443R3's blocking-related properties apply to all execution functions supported by the executor as a whole, so this issue has been clarified.
