### ISSUE TITLE
Difference between execute and sync_execute?

### ISSUE THREAD

**Issue by hkaiser** [executors/executors#98]
What is the difference between the customization points `execution::execute` and `execution::sync_execute`? Would it be possible to unify those?

**Comment by jaredhoberock** [comment]
`execution::execute()` possibly blocks its caller depending on `executor_execute_blocking_category_t`. The result of the function, if any, is discarded.

`execution::sync_execute()` always blocks and returns the result of the called function.

I'm not sure it's possible to unify the two given the blocking and result channeling behavior.

**Comment by ccmysen** [comment]
i think that the real difference is in the fact that one returns a value because it is guaranteed complete and the other does not. IIRC the use case was to allow for not having to create a future in this case because you are guaranteed execution is complete.

**Comment by jaredhoberock** [comment]
Explicitly synchronizing execution functions like `sync_execute` were eliminated because the `never_blocking` property made them superfluous.
