### ISSUE TITLE
thread_pool & thread_pool::executor wording

### ISSUE THREAD

**Issue by rodgert** [executors/executors#99]
Maybe this has already been discussed, I've missed the past few calls, but it seemed a bit odd.

In text for thread_pool -

"This pool provides an effectively unbounded input queue and as such calls to add tasks to a thread_pool's executor will not block on the input queue."

Yet, thread_pool itself has no direct interface for submitting tasks, that belongs to thread_pool::executor_type.

Should this comment belong to thread_pool::executor_type, where the work submission functionality resides?

**Comment by ccmysen** [comment]
I don't think that it really needs to move. It does attempt to make it clear that the unbounded input queue is about submitting tasks to the associated executor. Tweaking the wording to clarify that though.

**Comment by jaredhoberock** [comment]
@ccmysen can we close this issue, or does the wording you mentioned still need to be clarified?
